// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: earth/assembly/v1/assembly.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// VoteOption is one human's position on a ballot.
//
// There is deliberately no abstain. Approval is two thirds of the votes cast, so
// an abstention and a non-vote come to exactly the same arithmetic; offering
// both would only invite a voter to think they had done something different.
type VoteOption int32

const (
	// VOTE_OPTION_UNSPECIFIED is an invalid default; every vote must name a side.
	VOTE_OPTION_UNSPECIFIED VoteOption = 0
	VOTE_OPTION_YES         VoteOption = 1
	VOTE_OPTION_NO          VoteOption = 2
)

var VoteOption_name = map[int32]string{
	0: "VOTE_OPTION_UNSPECIFIED",
	1: "VOTE_OPTION_YES",
	2: "VOTE_OPTION_NO",
}

var VoteOption_value = map[string]int32{
	"VOTE_OPTION_UNSPECIFIED": 0,
	"VOTE_OPTION_YES":         1,
	"VOTE_OPTION_NO":          2,
}

func (x VoteOption) String() string {
	return proto.EnumName(VoteOption_name, int32(x))
}

func (VoteOption) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a143d9dbe28822e, []int{0}
}

// Tally is a ballot's running count. Votes are people, not weight: the whole
// point of this chamber is that there is no number attached to a human.
type Tally struct {
	Yes uint64 `protobuf:"varint,1,opt,name=yes,proto3" json:"yes,omitempty"`
	No  uint64 `protobuf:"varint,2,opt,name=no,proto3" json:"no,omitempty"`
}

func (m *Tally) Reset()         { *m = Tally{} }
func (m *Tally) String() string { return proto.CompactTextString(m) }
func (*Tally) ProtoMessage()    {}
func (*Tally) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a143d9dbe28822e, []int{0}
}
func (m *Tally) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tally) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tally.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tally) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tally.Merge(m, src)
}
func (m *Tally) XXX_Size() int {
	return m.Size()
}
func (m *Tally) XXX_DiscardUnknown() {
	xxx_messageInfo_Tally.DiscardUnknown(m)
}

var xxx_messageInfo_Tally proto.InternalMessageInfo

func (m *Tally) GetYes() uint64 {
	if m != nil {
		return m.Yes
	}
	return 0
}

func (m *Tally) GetNo() uint64 {
	if m != nil {
		return m.No
	}
	return 0
}

// RemovalBallot is an open vote to remove one groundworks allocation option.
//
// The stream is not recorded because there is only one it can be. Removal is the
// chamber's single affirmative power and it reaches the groundworks slate alone;
// the caretaker slate is directed by these same humans voting continuously, and
// has no need of a second instrument pointed at it.
type RemovalBallot struct {
	OptionId uint64 `protobuf:"varint,1,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	Proposer string `protobuf:"bytes,2,opt,name=proposer,proto3" json:"proposer,omitempty"`
	// closes_at is when voting ends, in unix seconds. The EndBlocker resolves the
	// ballot at the first block at or after it.
	ClosesAt int64 `protobuf:"varint,3,opt,name=closes_at,json=closesAt,proto3" json:"closes_at,omitempty"`
	Tally    Tally `protobuf:"bytes,4,opt,name=tally,proto3" json:"tally"`
}

func (m *RemovalBallot) Reset()         { *m = RemovalBallot{} }
func (m *RemovalBallot) String() string { return proto.CompactTextString(m) }
func (*RemovalBallot) ProtoMessage()    {}
func (*RemovalBallot) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a143d9dbe28822e, []int{1}
}
func (m *RemovalBallot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemovalBallot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemovalBallot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RemovalBallot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovalBallot.Merge(m, src)
}
func (m *RemovalBallot) XXX_Size() int {
	return m.Size()
}
func (m *RemovalBallot) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovalBallot.DiscardUnknown(m)
}

var xxx_messageInfo_RemovalBallot proto.InternalMessageInfo

func (m *RemovalBallot) GetOptionId() uint64 {
	if m != nil {
		return m.OptionId
	}
	return 0
}

func (m *RemovalBallot) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

func (m *RemovalBallot) GetClosesAt() int64 {
	if m != nil {
		return m.ClosesAt
	}
	return 0
}

func (m *RemovalBallot) GetTally() Tally {
	if m != nil {
		return m.Tally
	}
	return Tally{}
}

func init() {
	proto.RegisterEnum("earth.assembly.v1.VoteOption", VoteOption_name, VoteOption_value)
	proto.RegisterType((*Tally)(nil), "earth.assembly.v1.Tally")
	proto.RegisterType((*RemovalBallot)(nil), "earth.assembly.v1.RemovalBallot")
}

func init() { proto.RegisterFile("earth/assembly/v1/assembly.proto", fileDescriptor_6a143d9dbe28822e) }

var fileDescriptor_6a143d9dbe28822e = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0xae, 0x93, 0x40,
	0x14, 0x86, 0x19, 0xca, 0x35, 0xbd, 0x63, 0xbc, 0xe2, 0x78, 0x13, 0xb1, 0x37, 0x41, 0x72, 0x57,
	0xd5, 0xa4, 0x90, 0x6a, 0x5f, 0xa0, 0x28, 0x26, 0x6c, 0x4a, 0x43, 0x6b, 0xa3, 0x6e, 0x08, 0x2d,
	0x13, 0x4a, 0x04, 0x0e, 0x61, 0xc6, 0x2a, 0x6f, 0xe0, 0xd2, 0x77, 0xf0, 0x15, 0xf4, 0x1d, 0xba,
	0x6c, 0x5c, 0xb9, 0x32, 0xa6, 0x7d, 0x11, 0xc3, 0x4c, 0x53, 0x9b, 0xb8, 0x3b, 0xe7, 0x9b, 0x6f,
	0x4e, 0xfe, 0x99, 0x83, 0x2d, 0x1a, 0xd7, 0x7c, 0xed, 0xc4, 0x8c, 0xd1, 0x62, 0x99, 0x37, 0xce,
	0x66, 0x78, 0xaa, 0xed, 0xaa, 0x06, 0x0e, 0xe4, 0x81, 0x30, 0xec, 0x13, 0xdd, 0x0c, 0x7b, 0x8f,
	0x57, 0xc0, 0x0a, 0x60, 0x91, 0x10, 0x1c, 0xd9, 0x48, 0xbb, 0x77, 0x9d, 0x42, 0x0a, 0x92, 0xb7,
	0x95, 0xa4, 0xb7, 0x4f, 0xf1, 0xc5, 0x3c, 0xce, 0xf3, 0x86, 0xe8, 0xb8, 0xd3, 0x50, 0x66, 0x20,
	0x0b, 0xf5, 0xb5, 0xb0, 0x2d, 0xc9, 0x15, 0x56, 0x4b, 0x30, 0x54, 0x01, 0xd4, 0x12, 0x6e, 0x7f,
	0x20, 0x7c, 0x2f, 0xa4, 0x05, 0x6c, 0xe2, 0xdc, 0x8d, 0xf3, 0x1c, 0x38, 0xb9, 0xc1, 0x97, 0x50,
	0xf1, 0x0c, 0xca, 0x28, 0x4b, 0x8e, 0x37, 0xbb, 0x12, 0xf8, 0x09, 0x19, 0xe1, 0x6e, 0x55, 0x43,
	0x05, 0x8c, 0xd6, 0x62, 0xc8, 0xa5, 0x6b, 0xfc, 0xfc, 0x3e, 0xb8, 0x3e, 0x66, 0x1a, 0x27, 0x49,
	0x4d, 0x19, 0x9b, 0xf1, 0x3a, 0x2b, 0xd3, 0xf0, 0x64, 0xb6, 0x23, 0x57, 0x39, 0x30, 0xca, 0xa2,
	0x98, 0x1b, 0x1d, 0x0b, 0xf5, 0x3b, 0x61, 0x57, 0x82, 0x31, 0x27, 0x23, 0x7c, 0xc1, 0xdb, 0xb0,
	0x86, 0x66, 0xa1, 0xfe, 0xdd, 0xe7, 0x86, 0xfd, 0xdf, 0x07, 0xd8, 0xe2, 0x31, 0xae, 0xb6, 0xfd,
	0xfd, 0x44, 0x09, 0xa5, 0xfc, 0xec, 0x2d, 0xc6, 0x0b, 0xe0, 0x34, 0x10, 0xc1, 0xc8, 0x0d, 0x7e,
	0xb4, 0x08, 0xe6, 0x5e, 0x14, 0x4c, 0xe7, 0x7e, 0x30, 0x89, 0xde, 0x4c, 0x66, 0x53, 0xef, 0xa5,
	0xff, 0xda, 0xf7, 0x5e, 0xe9, 0x0a, 0x79, 0x88, 0xef, 0x9f, 0x1f, 0xbe, 0xf3, 0x66, 0x3a, 0x22,
	0x04, 0x5f, 0x9d, 0xc3, 0x49, 0xa0, 0xab, 0x3d, 0xed, 0xcb, 0x37, 0x53, 0x71, 0xfd, 0xed, 0xde,
	0x44, 0xbb, 0xbd, 0x89, 0xfe, 0xec, 0x4d, 0xf4, 0xf5, 0x60, 0x2a, 0xbb, 0x83, 0xa9, 0xfc, 0x3a,
	0x98, 0xca, 0x7b, 0x27, 0xcd, 0xf8, 0xfa, 0xe3, 0xd2, 0x5e, 0x41, 0xe1, 0x88, 0x90, 0x83, 0x92,
	0xf2, 0x4f, 0x50, 0x7f, 0x90, 0x9d, 0xf3, 0xf9, 0xdf, 0x5e, 0x79, 0x53, 0x51, 0xb6, 0xbc, 0x23,
	0xd6, 0xf1, 0xe2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x28, 0x19, 0x55, 0xf6, 0x01, 0x00,
	0x00,
}

func (m *Tally) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tally) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tally) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.No != 0 {
		i = encodeVarintAssembly(dAtA, i, uint64(m.No))
		i--
		dAtA[i] = 0x10
	}
	if m.Yes != 0 {
		i = encodeVarintAssembly(dAtA, i, uint64(m.Yes))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RemovalBallot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemovalBallot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RemovalBallot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Tally.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAssembly(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.ClosesAt != 0 {
		i = encodeVarintAssembly(dAtA, i, uint64(m.ClosesAt))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Proposer) > 0 {
		i -= len(m.Proposer)
		copy(dAtA[i:], m.Proposer)
		i = encodeVarintAssembly(dAtA, i, uint64(len(m.Proposer)))
		i--
		dAtA[i] = 0x12
	}
	if m.OptionId != 0 {
		i = encodeVarintAssembly(dAtA, i, uint64(m.OptionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAssembly(dAtA []byte, offset int, v uint64) int {
	offset -= sovAssembly(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Tally) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Yes != 0 {
		n += 1 + sovAssembly(uint64(m.Yes))
	}
	if m.No != 0 {
		n += 1 + sovAssembly(uint64(m.No))
	}
	return n
}

func (m *RemovalBallot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OptionId != 0 {
		n += 1 + sovAssembly(uint64(m.OptionId))
	}
	l = len(m.Proposer)
	if l > 0 {
		n += 1 + l + sovAssembly(uint64(l))
	}
	if m.ClosesAt != 0 {
		n += 1 + sovAssembly(uint64(m.ClosesAt))
	}
	l = m.Tally.Size()
	n += 1 + l + sovAssembly(uint64(l))
	return n
}

func sovAssembly(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAssembly(x uint64) (n int) {
	return sovAssembly(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Tally) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAssembly
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tally: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tally: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Yes", wireType)
			}
			m.Yes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssembly
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Yes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field No", wireType)
			}
			m.No = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssembly
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.No |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAssembly(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAssembly
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemovalBallot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAssembly
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemovalBallot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemovalBallot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OptionId", wireType)
			}
			m.OptionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssembly
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OptionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssembly
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAssembly
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAssembly
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClosesAt", wireType)
			}
			m.ClosesAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssembly
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClosesAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tally", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssembly
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAssembly
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAssembly
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tally.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAssembly(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAssembly
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAssembly(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAssembly
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAssembly
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAssembly
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAssembly
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAssembly
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAssembly
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAssembly        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAssembly          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAssembly = fmt.Errorf("proto: unexpected end of group")
)
