// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: earth/assembly/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryBallotInputsRequest struct {
	ProposalId uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	OptionId   uint64 `protobuf:"varint,2,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
}

func (m *QueryBallotInputsRequest) Reset()         { *m = QueryBallotInputsRequest{} }
func (m *QueryBallotInputsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBallotInputsRequest) ProtoMessage()    {}
func (*QueryBallotInputsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccc0ba4852d53c2d, []int{0}
}
func (m *QueryBallotInputsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBallotInputsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBallotInputsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBallotInputsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBallotInputsRequest.Merge(m, src)
}
func (m *QueryBallotInputsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBallotInputsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBallotInputsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBallotInputsRequest proto.InternalMessageInfo

func (m *QueryBallotInputsRequest) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *QueryBallotInputsRequest) GetOptionId() uint64 {
	if m != nil {
		return m.OptionId
	}
	return 0
}

type QueryBallotInputsResponse struct {
	Scope         []byte `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	ExcludedDsc   []byte `protobuf:"bytes,2,opt,name=excluded_dsc,json=excludedDsc,proto3" json:"excluded_dsc,omitempty"`
	MaxActivation uint64 `protobuf:"varint,3,opt,name=max_activation,json=maxActivation,proto3" json:"max_activation,omitempty"`
	Round         uint64 `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	BallotId      uint64 `protobuf:"varint,5,opt,name=ballot_id,json=ballotId,proto3" json:"ballot_id,omitempty"`
}

func (m *QueryBallotInputsResponse) Reset()         { *m = QueryBallotInputsResponse{} }
func (m *QueryBallotInputsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBallotInputsResponse) ProtoMessage()    {}
func (*QueryBallotInputsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccc0ba4852d53c2d, []int{1}
}
func (m *QueryBallotInputsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBallotInputsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBallotInputsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBallotInputsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBallotInputsResponse.Merge(m, src)
}
func (m *QueryBallotInputsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBallotInputsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBallotInputsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBallotInputsResponse proto.InternalMessageInfo

func (m *QueryBallotInputsResponse) GetScope() []byte {
	if m != nil {
		return m.Scope
	}
	return nil
}

func (m *QueryBallotInputsResponse) GetExcludedDsc() []byte {
	if m != nil {
		return m.ExcludedDsc
	}
	return nil
}

func (m *QueryBallotInputsResponse) GetMaxActivation() uint64 {
	if m != nil {
		return m.MaxActivation
	}
	return 0
}

func (m *QueryBallotInputsResponse) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *QueryBallotInputsResponse) GetBallotId() uint64 {
	if m != nil {
		return m.BallotId
	}
	return 0
}

type QueryProposalTallyRequest struct {
	ProposalId uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
}

func (m *QueryProposalTallyRequest) Reset()         { *m = QueryProposalTallyRequest{} }
func (m *QueryProposalTallyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProposalTallyRequest) ProtoMessage()    {}
func (*QueryProposalTallyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccc0ba4852d53c2d, []int{2}
}
func (m *QueryProposalTallyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProposalTallyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProposalTallyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProposalTallyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProposalTallyRequest.Merge(m, src)
}
func (m *QueryProposalTallyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryProposalTallyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProposalTallyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProposalTallyRequest proto.InternalMessageInfo

func (m *QueryProposalTallyRequest) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

type QueryProposalTallyResponse struct {
	Tally Tally `protobuf:"bytes,1,opt,name=tally,proto3" json:"tally"`
	// approved reports whether the tally as it stands clears two thirds. A
	// proposal with no human votes is not approved — silence is not assent here.
	Approved bool `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
}

func (m *QueryProposalTallyResponse) Reset()         { *m = QueryProposalTallyResponse{} }
func (m *QueryProposalTallyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryProposalTallyResponse) ProtoMessage()    {}
func (*QueryProposalTallyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccc0ba4852d53c2d, []int{3}
}
func (m *QueryProposalTallyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProposalTallyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProposalTallyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProposalTallyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProposalTallyResponse.Merge(m, src)
}
func (m *QueryProposalTallyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryProposalTallyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProposalTallyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProposalTallyResponse proto.InternalMessageInfo

func (m *QueryProposalTallyResponse) GetTally() Tally {
	if m != nil {
		return m.Tally
	}
	return Tally{}
}

func (m *QueryProposalTallyResponse) GetApproved() bool {
	if m != nil {
		return m.Approved
	}
	return false
}

type QueryRemovalBallotsRequest struct {
}

func (m *QueryRemovalBallotsRequest) Reset()         { *m = QueryRemovalBallotsRequest{} }
func (m *QueryRemovalBallotsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRemovalBallotsRequest) ProtoMessage()    {}
func (*QueryRemovalBallotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccc0ba4852d53c2d, []int{4}
}
func (m *QueryRemovalBallotsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRemovalBallotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRemovalBallotsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRemovalBallotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRemovalBallotsRequest.Merge(m, src)
}
func (m *QueryRemovalBallotsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRemovalBallotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRemovalBallotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRemovalBallotsRequest proto.InternalMessageInfo

type QueryRemovalBallotsResponse struct {
	Ballots []RemovalBallot `protobuf:"bytes,1,rep,name=ballots,proto3" json:"ballots"`
}

func (m *QueryRemovalBallotsResponse) Reset()         { *m = QueryRemovalBallotsResponse{} }
func (m *QueryRemovalBallotsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRemovalBallotsResponse) ProtoMessage()    {}
func (*QueryRemovalBallotsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccc0ba4852d53c2d, []int{5}
}
func (m *QueryRemovalBallotsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRemovalBallotsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRemovalBallotsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRemovalBallotsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRemovalBallotsResponse.Merge(m, src)
}
func (m *QueryRemovalBallotsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRemovalBallotsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRemovalBallotsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRemovalBallotsResponse proto.InternalMessageInfo

func (m *QueryRemovalBallotsResponse) GetBallots() []RemovalBallot {
	if m != nil {
		return m.Ballots
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryBallotInputsRequest)(nil), "earth.assembly.v1.QueryBallotInputsRequest")
	proto.RegisterType((*QueryBallotInputsResponse)(nil), "earth.assembly.v1.QueryBallotInputsResponse")
	proto.RegisterType((*QueryProposalTallyRequest)(nil), "earth.assembly.v1.QueryProposalTallyRequest")
	proto.RegisterType((*QueryProposalTallyResponse)(nil), "earth.assembly.v1.QueryProposalTallyResponse")
	proto.RegisterType((*QueryRemovalBallotsRequest)(nil), "earth.assembly.v1.QueryRemovalBallotsRequest")
	proto.RegisterType((*QueryRemovalBallotsResponse)(nil), "earth.assembly.v1.QueryRemovalBallotsResponse")
}

func init() { proto.RegisterFile("earth/assembly/v1/query.proto", fileDescriptor_ccc0ba4852d53c2d) }

var fileDescriptor_ccc0ba4852d53c2d = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xb1, 0x8f, 0xd3, 0x3e,
	0x18, 0xad, 0xaf, 0xed, 0xef, 0x57, 0xdc, 0xde, 0x49, 0x58, 0x37, 0x84, 0xdc, 0x91, 0x2b, 0x11,
	0x48, 0x15, 0xdc, 0xc5, 0x6a, 0x41, 0x62, 0x61, 0x80, 0x8a, 0xa5, 0x1b, 0x44, 0x0c, 0x88, 0xa5,
	0x72, 0x13, 0xab, 0x57, 0x91, 0xc6, 0xbe, 0xd8, 0x09, 0xad, 0x10, 0x0b, 0x7f, 0x01, 0xd2, 0x8d,
	0xcc, 0xac, 0xfc, 0x1d, 0x37, 0x9e, 0xc4, 0xc2, 0x84, 0x50, 0xcb, 0x1f, 0x82, 0x62, 0x3b, 0xe5,
	0xaa, 0xa6, 0x52, 0xb7, 0xf8, 0x7b, 0x7e, 0xef, 0x7b, 0xdf, 0xb3, 0xbe, 0xc0, 0xbb, 0x94, 0x24,
	0xf2, 0x1c, 0x13, 0x21, 0xe8, 0x74, 0x14, 0xcd, 0x71, 0xd6, 0xc5, 0x17, 0x29, 0x4d, 0xe6, 0x1e,
	0x4f, 0x98, 0x64, 0xe8, 0xb6, 0x82, 0xbd, 0x02, 0xf6, 0xb2, 0xae, 0xdd, 0xde, 0x64, 0xac, 0x60,
	0x45, 0xb2, 0x0f, 0xc7, 0x6c, 0xcc, 0xd4, 0x27, 0xce, 0xbf, 0x4c, 0xf5, 0x78, 0xcc, 0xd8, 0x38,
	0xa2, 0x98, 0xf0, 0x09, 0x26, 0x71, 0xcc, 0x24, 0x91, 0x13, 0x16, 0x0b, 0x8d, 0xba, 0x6f, 0xa1,
	0xf5, 0x3a, 0xef, 0xdb, 0x27, 0x51, 0xc4, 0xe4, 0x20, 0xe6, 0xa9, 0x14, 0x3e, 0xbd, 0x48, 0xa9,
	0x90, 0xe8, 0x04, 0x36, 0x79, 0xc2, 0x38, 0x13, 0x24, 0x1a, 0x4e, 0x42, 0x0b, 0xb4, 0x41, 0xa7,
	0xe6, 0xc3, 0xa2, 0x34, 0x08, 0xd1, 0x11, 0xbc, 0xc5, 0x78, 0xae, 0x96, 0xc3, 0x7b, 0x0a, 0x6e,
	0xe8, 0xc2, 0x20, 0x74, 0xbf, 0x03, 0x78, 0xa7, 0x44, 0x5a, 0x70, 0x16, 0x0b, 0x8a, 0x0e, 0x61,
	0x5d, 0x04, 0x8c, 0x53, 0xa5, 0xda, 0xf2, 0xf5, 0x01, 0xdd, 0x83, 0x2d, 0x3a, 0x0b, 0xa2, 0x34,
	0xa4, 0xe1, 0x30, 0x14, 0x81, 0xd2, 0x6c, 0xf9, 0xcd, 0xa2, 0xf6, 0x52, 0x04, 0xe8, 0x01, 0x3c,
	0x98, 0x92, 0xd9, 0x90, 0x04, 0x72, 0x92, 0xa9, 0x49, 0xac, 0xaa, 0x6a, 0xbc, 0x3f, 0x25, 0xb3,
	0x17, 0xab, 0x62, 0xae, 0x9f, 0xb0, 0x34, 0x0e, 0xad, 0x9a, 0x42, 0xf5, 0x21, 0x37, 0x3c, 0x52,
	0x6e, 0x72, 0xc3, 0x75, 0x6d, 0x58, 0x17, 0x06, 0xa1, 0xfb, 0xcc, 0xf8, 0x7d, 0x65, 0x06, 0x7c,
	0x43, 0xa2, 0x68, 0xbe, 0x6b, 0x16, 0x6e, 0x0c, 0xed, 0x32, 0xb6, 0x19, 0xf7, 0x09, 0xac, 0xcb,
	0xbc, 0xa0, 0x88, 0xcd, 0x9e, 0xe5, 0x6d, 0xbc, 0xaf, 0xa7, 0x08, 0xfd, 0xda, 0xd5, 0xaf, 0x93,
	0x8a, 0xaf, 0x2f, 0x23, 0x1b, 0x36, 0x08, 0xe7, 0x09, 0xcb, 0xa8, 0x8e, 0xb7, 0xe1, 0xaf, 0xce,
	0xee, 0xb1, 0xe9, 0xe7, 0xd3, 0x29, 0xcb, 0x48, 0xa4, 0x43, 0x2e, 0x9e, 0xce, 0x1d, 0xc2, 0xa3,
	0x52, 0xd4, 0xd8, 0x79, 0x0e, 0xff, 0xd7, 0x63, 0x0b, 0x0b, 0xb4, 0xab, 0x9d, 0x66, 0xaf, 0x5d,
	0x62, 0x68, 0x8d, 0x6b, 0x8c, 0x15, 0xb4, 0xde, 0xb2, 0x0a, 0xeb, 0xaa, 0x03, 0xfa, 0x06, 0xe0,
	0xfe, 0xda, 0xd0, 0xe8, 0xb4, 0x44, 0x6c, 0x6b, 0xb2, 0xf6, 0xd9, 0x8e, 0xb7, 0xb5, 0x75, 0xf7,
	0xe9, 0xe7, 0x1f, 0x7f, 0x2e, 0xf7, 0xba, 0x08, 0xe3, 0xcd, 0x7d, 0x58, 0xbd, 0x90, 0x8a, 0x0f,
	0x7f, 0xbc, 0xf1, 0x62, 0x9f, 0xd0, 0x57, 0x00, 0x0f, 0xd6, 0xe3, 0x40, 0x5b, 0x5b, 0x97, 0x86,
	0x6a, 0x7b, 0xbb, 0x5e, 0x37, 0x56, 0x1f, 0x2a, 0xab, 0xf7, 0x91, 0x5b, 0x62, 0x35, 0xd1, 0x94,
	0xa1, 0xc9, 0x13, 0x5d, 0x02, 0xd8, 0xba, 0xb9, 0x28, 0xe8, 0xd1, 0xb6, 0x66, 0x25, 0x9b, 0x6a,
	0x9f, 0xee, 0x76, 0xd9, 0xf8, 0xea, 0x28, 0x5f, 0x2e, 0x6a, 0x97, 0xf8, 0x2a, 0xd6, 0x43, 0x31,
	0xfa, 0x83, 0xab, 0x85, 0x03, 0xae, 0x17, 0x0e, 0xf8, 0xbd, 0x70, 0xc0, 0x97, 0xa5, 0x53, 0xb9,
	0x5e, 0x3a, 0x95, 0x9f, 0x4b, 0xa7, 0xf2, 0x0e, 0x8f, 0x27, 0xf2, 0x3c, 0x1d, 0x79, 0x01, 0x9b,
	0x6a, 0x95, 0xb3, 0x98, 0xca, 0x0f, 0x2c, 0x79, 0x6f, 0x34, 0x67, 0xff, 0x54, 0xe5, 0x9c, 0x53,
	0x31, 0xfa, 0x4f, 0xfd, 0x6f, 0x1e, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x82, 0xb7, 0xac, 0x9f,
	0xf9, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// ProposalTally returns the human tally on an x/gov proposal, and whether it
	// currently clears the two-thirds bar.
	ProposalTally(ctx context.Context, in *QueryProposalTallyRequest, opts ...grpc.CallOption) (*QueryProposalTallyResponse, error)
	// RemovalBallots lists every open removal ballot.
	RemovalBallots(ctx context.Context, in *QueryRemovalBallotsRequest, opts ...grpc.CallOption) (*QueryRemovalBallotsResponse, error)
	// BallotInputs returns the membership public inputs a vote on a proposal's
	// current round (proposal_id set) or on an option's open removal ballot
	// (option_id set) must be proven against.
	BallotInputs(ctx context.Context, in *QueryBallotInputsRequest, opts ...grpc.CallOption) (*QueryBallotInputsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ProposalTally(ctx context.Context, in *QueryProposalTallyRequest, opts ...grpc.CallOption) (*QueryProposalTallyResponse, error) {
	out := new(QueryProposalTallyResponse)
	err := c.cc.Invoke(ctx, "/earth.assembly.v1.Query/ProposalTally", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RemovalBallots(ctx context.Context, in *QueryRemovalBallotsRequest, opts ...grpc.CallOption) (*QueryRemovalBallotsResponse, error) {
	out := new(QueryRemovalBallotsResponse)
	err := c.cc.Invoke(ctx, "/earth.assembly.v1.Query/RemovalBallots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BallotInputs(ctx context.Context, in *QueryBallotInputsRequest, opts ...grpc.CallOption) (*QueryBallotInputsResponse, error) {
	out := new(QueryBallotInputsResponse)
	err := c.cc.Invoke(ctx, "/earth.assembly.v1.Query/BallotInputs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// ProposalTally returns the human tally on an x/gov proposal, and whether it
	// currently clears the two-thirds bar.
	ProposalTally(context.Context, *QueryProposalTallyRequest) (*QueryProposalTallyResponse, error)
	// RemovalBallots lists every open removal ballot.
	RemovalBallots(context.Context, *QueryRemovalBallotsRequest) (*QueryRemovalBallotsResponse, error)
	// BallotInputs returns the membership public inputs a vote on a proposal's
	// current round (proposal_id set) or on an option's open removal ballot
	// (option_id set) must be proven against.
	BallotInputs(context.Context, *QueryBallotInputsRequest) (*QueryBallotInputsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ProposalTally(ctx context.Context, req *QueryProposalTallyRequest) (*QueryProposalTallyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposalTally not implemented")
}
func (*UnimplementedQueryServer) RemovalBallots(ctx context.Context, req *QueryRemovalBallotsRequest) (*QueryRemovalBallotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovalBallots not implemented")
}
func (*UnimplementedQueryServer) BallotInputs(ctx context.Context, req *QueryBallotInputsRequest) (*QueryBallotInputsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BallotInputs not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ProposalTally_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProposalTallyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ProposalTally(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.assembly.v1.Query/ProposalTally",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ProposalTally(ctx, req.(*QueryProposalTallyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RemovalBallots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRemovalBallotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RemovalBallots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.assembly.v1.Query/RemovalBallots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RemovalBallots(ctx, req.(*QueryRemovalBallotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BallotInputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBallotInputsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BallotInputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.assembly.v1.Query/BallotInputs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BallotInputs(ctx, req.(*QueryBallotInputsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "earth.assembly.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProposalTally",
			Handler:    _Query_ProposalTally_Handler,
		},
		{
			MethodName: "RemovalBallots",
			Handler:    _Query_RemovalBallots_Handler,
		},
		{
			MethodName: "BallotInputs",
			Handler:    _Query_BallotInputs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "earth/assembly/v1/query.proto",
}

func (m *QueryBallotInputsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBallotInputsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBallotInputsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OptionId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.OptionId))
		i--
		dAtA[i] = 0x10
	}
	if m.ProposalId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryBallotInputsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBallotInputsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBallotInputsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BallotId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BallotId))
		i--
		dAtA[i] = 0x28
	}
	if m.Round != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxActivation != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MaxActivation))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ExcludedDsc) > 0 {
		i -= len(m.ExcludedDsc)
		copy(dAtA[i:], m.ExcludedDsc)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ExcludedDsc)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Scope) > 0 {
		i -= len(m.Scope)
		copy(dAtA[i:], m.Scope)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Scope)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryProposalTallyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProposalTallyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProposalTallyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProposalId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryProposalTallyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProposalTallyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProposalTallyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Approved {
		i--
		if m.Approved {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Tally.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRemovalBallotsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRemovalBallotsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRemovalBallotsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryRemovalBallotsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRemovalBallotsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRemovalBallotsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ballots) > 0 {
		for iNdEx := len(m.Ballots) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Ballots[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryBallotInputsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProposalId != 0 {
		n += 1 + sovQuery(uint64(m.ProposalId))
	}
	if m.OptionId != 0 {
		n += 1 + sovQuery(uint64(m.OptionId))
	}
	return n
}

func (m *QueryBallotInputsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Scope)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ExcludedDsc)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.MaxActivation != 0 {
		n += 1 + sovQuery(uint64(m.MaxActivation))
	}
	if m.Round != 0 {
		n += 1 + sovQuery(uint64(m.Round))
	}
	if m.BallotId != 0 {
		n += 1 + sovQuery(uint64(m.BallotId))
	}
	return n
}

func (m *QueryProposalTallyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProposalId != 0 {
		n += 1 + sovQuery(uint64(m.ProposalId))
	}
	return n
}

func (m *QueryProposalTallyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Tally.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.Approved {
		n += 2
	}
	return n
}

func (m *QueryRemovalBallotsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryRemovalBallotsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ballots) > 0 {
		for _, e := range m.Ballots {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryBallotInputsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBallotInputsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBallotInputsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OptionId", wireType)
			}
			m.OptionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OptionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBallotInputsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBallotInputsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBallotInputsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scope", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scope = append(m.Scope[:0], dAtA[iNdEx:postIndex]...)
			if m.Scope == nil {
				m.Scope = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExcludedDsc", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExcludedDsc = append(m.ExcludedDsc[:0], dAtA[iNdEx:postIndex]...)
			if m.ExcludedDsc == nil {
				m.ExcludedDsc = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxActivation", wireType)
			}
			m.MaxActivation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxActivation |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotId", wireType)
			}
			m.BallotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BallotId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProposalTallyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProposalTallyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProposalTallyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProposalTallyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProposalTallyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProposalTallyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tally", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tally.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approved", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Approved = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRemovalBallotsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRemovalBallotsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRemovalBallotsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRemovalBallotsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRemovalBallotsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRemovalBallotsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ballots", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ballots = append(m.Ballots, RemovalBallot{})
			if err := m.Ballots[len(m.Ballots)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
