# Release: https://github.com/zenopie/earth-network-chain/releases/tag/v0.0.5
# Workflow URL: https://github.com/zenopie/earth-network-chain/actions/runs/31956600367
# Commit: https://github.com/zenopie/earth-network-chain/commit/5b5d77d3d50e82ef48387b23d8c59b34d0494480
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-chain@sha256:840a7601c11a002cdfca2fb74104dcf97af173dbab33c705d4334b6602590e94
    ports:
      - '1317'
      - '26657'
