// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: earth/deflation/v1/query.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66950fc10c33fc8d, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66950fc10c33fc8d, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryAllocationOptionRequest requests a single allocation option.
type QueryAllocationOptionRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryAllocationOptionRequest) Reset()         { *m = QueryAllocationOptionRequest{} }
func (m *QueryAllocationOptionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllocationOptionRequest) ProtoMessage()    {}
func (*QueryAllocationOptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66950fc10c33fc8d, []int{2}
}
func (m *QueryAllocationOptionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllocationOptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllocationOptionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllocationOptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllocationOptionRequest.Merge(m, src)
}
func (m *QueryAllocationOptionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllocationOptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllocationOptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllocationOptionRequest proto.InternalMessageInfo

func (m *QueryAllocationOptionRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// QueryAllocationOptionResponse returns a single allocation option.
type QueryAllocationOptionResponse struct {
	Option AllocationOption `protobuf:"bytes,1,opt,name=option,proto3" json:"option"`
}

func (m *QueryAllocationOptionResponse) Reset()         { *m = QueryAllocationOptionResponse{} }
func (m *QueryAllocationOptionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllocationOptionResponse) ProtoMessage()    {}
func (*QueryAllocationOptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66950fc10c33fc8d, []int{3}
}
func (m *QueryAllocationOptionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllocationOptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllocationOptionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllocationOptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllocationOptionResponse.Merge(m, src)
}
func (m *QueryAllocationOptionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllocationOptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllocationOptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllocationOptionResponse proto.InternalMessageInfo

func (m *QueryAllocationOptionResponse) GetOption() AllocationOption {
	if m != nil {
		return m.Option
	}
	return AllocationOption{}
}

// QueryAllocationOptionsRequest requests all allocation options.
type QueryAllocationOptionsRequest struct {
}

func (m *QueryAllocationOptionsRequest) Reset()         { *m = QueryAllocationOptionsRequest{} }
func (m *QueryAllocationOptionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllocationOptionsRequest) ProtoMessage()    {}
func (*QueryAllocationOptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66950fc10c33fc8d, []int{4}
}
func (m *QueryAllocationOptionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllocationOptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllocationOptionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllocationOptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllocationOptionsRequest.Merge(m, src)
}
func (m *QueryAllocationOptionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllocationOptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllocationOptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllocationOptionsRequest proto.InternalMessageInfo

// QueryAllocationOptionsResponse returns all allocation options.
type QueryAllocationOptionsResponse struct {
	Options []AllocationOption `protobuf:"bytes,1,rep,name=options,proto3" json:"options"`
	// reward_index is the current global allocation reward index.
	RewardIndex cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=reward_index,json=rewardIndex,proto3,customtype=cosmossdk.io/math.Int" json:"reward_index"`
	// total_weight is the total stake weight currently allocating.
	TotalWeight cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=total_weight,json=totalWeight,proto3,customtype=cosmossdk.io/math.Int" json:"total_weight"`
}

func (m *QueryAllocationOptionsResponse) Reset()         { *m = QueryAllocationOptionsResponse{} }
func (m *QueryAllocationOptionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllocationOptionsResponse) ProtoMessage()    {}
func (*QueryAllocationOptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66950fc10c33fc8d, []int{5}
}
func (m *QueryAllocationOptionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllocationOptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllocationOptionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllocationOptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllocationOptionsResponse.Merge(m, src)
}
func (m *QueryAllocationOptionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllocationOptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllocationOptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllocationOptionsResponse proto.InternalMessageInfo

func (m *QueryAllocationOptionsResponse) GetOptions() []AllocationOption {
	if m != nil {
		return m.Options
	}
	return nil
}

// QueryVoterRequest requests a voter's allocation split.
type QueryVoterRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryVoterRequest) Reset()         { *m = QueryVoterRequest{} }
func (m *QueryVoterRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVoterRequest) ProtoMessage()    {}
func (*QueryVoterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66950fc10c33fc8d, []int{6}
}
func (m *QueryVoterRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVoterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVoterRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVoterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVoterRequest.Merge(m, src)
}
func (m *QueryVoterRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVoterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVoterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVoterRequest proto.InternalMessageInfo

func (m *QueryVoterRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryVoterResponse returns a voter's allocation split.
type QueryVoterResponse struct {
	Voter Voter `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter"`
}

func (m *QueryVoterResponse) Reset()         { *m = QueryVoterResponse{} }
func (m *QueryVoterResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVoterResponse) ProtoMessage()    {}
func (*QueryVoterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66950fc10c33fc8d, []int{7}
}
func (m *QueryVoterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVoterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVoterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVoterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVoterResponse.Merge(m, src)
}
func (m *QueryVoterResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVoterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVoterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVoterResponse proto.InternalMessageInfo

func (m *QueryVoterResponse) GetVoter() Voter {
	if m != nil {
		return m.Voter
	}
	return Voter{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "earth.deflation.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "earth.deflation.v1.QueryParamsResponse")
	proto.RegisterType((*QueryAllocationOptionRequest)(nil), "earth.deflation.v1.QueryAllocationOptionRequest")
	proto.RegisterType((*QueryAllocationOptionResponse)(nil), "earth.deflation.v1.QueryAllocationOptionResponse")
	proto.RegisterType((*QueryAllocationOptionsRequest)(nil), "earth.deflation.v1.QueryAllocationOptionsRequest")
	proto.RegisterType((*QueryAllocationOptionsResponse)(nil), "earth.deflation.v1.QueryAllocationOptionsResponse")
	proto.RegisterType((*QueryVoterRequest)(nil), "earth.deflation.v1.QueryVoterRequest")
	proto.RegisterType((*QueryVoterResponse)(nil), "earth.deflation.v1.QueryVoterResponse")
}

func init() { proto.RegisterFile("earth/deflation/v1/query.proto", fileDescriptor_66950fc10c33fc8d) }

var fileDescriptor_66950fc10c33fc8d = []byte{
	// 659 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x6b, 0x13, 0x4f,
	0x18, 0xce, 0xa6, 0x4d, 0x4a, 0xa7, 0x3f, 0x7e, 0xd8, 0xb1, 0x42, 0xba, 0xd4, 0x4d, 0x59, 0xb5,
	0x96, 0x4a, 0x77, 0x92, 0x54, 0x45, 0x45, 0xc1, 0x2e, 0x82, 0x44, 0xc1, 0x3f, 0xab, 0x28, 0x78,
	0x09, 0xd3, 0xec, 0xb8, 0x59, 0x9a, 0xec, 0x6c, 0x77, 0x27, 0x49, 0x4b, 0xe9, 0xc5, 0x83, 0x17,
	0x2f, 0x8a, 0x5f, 0xc0, 0xa3, 0x47, 0x0f, 0x3d, 0xe8, 0x37, 0xe8, 0xb1, 0xd4, 0x8b, 0x78, 0x28,
	0x92, 0x08, 0x7e, 0x0d, 0xd9, 0x99, 0x49, 0xac, 0xcd, 0x2e, 0x31, 0xbd, 0x2c, 0xbb, 0xf3, 0x3e,
	0xcf, 0xf3, 0x3e, 0xf3, 0xce, 0xb3, 0x03, 0x34, 0x82, 0x03, 0x56, 0x43, 0x36, 0x79, 0x59, 0xc7,
	0xcc, 0xa5, 0x1e, 0x6a, 0x15, 0xd1, 0x46, 0x93, 0x04, 0x5b, 0x86, 0x1f, 0x50, 0x46, 0x21, 0xe4,
	0x75, 0xa3, 0x5f, 0x37, 0x5a, 0x45, 0x75, 0x1a, 0x37, 0x5c, 0x8f, 0x22, 0xfe, 0x14, 0x30, 0x75,
	0xb6, 0x4a, 0xc3, 0x06, 0x0d, 0x2b, 0xfc, 0x0b, 0x89, 0x0f, 0x59, 0x3a, 0x17, 0xd3, 0x01, 0xd7,
	0xeb, 0xb4, 0x2a, 0xf4, 0x04, 0x28, 0x1f, 0x03, 0xf2, 0x71, 0x80, 0x1b, 0x3d, 0x95, 0x19, 0x87,
	0x3a, 0x54, 0xa8, 0x47, 0x6f, 0x72, 0x75, 0xce, 0xa1, 0xd4, 0xa9, 0x13, 0x84, 0x7d, 0x17, 0x61,
	0xcf, 0xa3, 0x8c, 0x93, 0x25, 0x47, 0x9f, 0x01, 0xf0, 0x71, 0xb4, 0x95, 0x47, 0x5c, 0xc8, 0x22,
	0x1b, 0x4d, 0x12, 0x32, 0xfd, 0x29, 0x38, 0xfd, 0xd7, 0x6a, 0xe8, 0x53, 0x2f, 0x24, 0xf0, 0x16,
	0xc8, 0x8a, 0x86, 0x39, 0x65, 0x5e, 0x59, 0x9c, 0x2a, 0xa9, 0xc6, 0xe0, 0xce, 0x0d, 0xc1, 0x31,
	0x27, 0xf7, 0x0e, 0xf3, 0xa9, 0x8f, 0xbf, 0x3e, 0x2d, 0x29, 0x96, 0x24, 0xe9, 0x06, 0x98, 0xe3,
	0xaa, 0xab, 0xfd, 0x9d, 0x3d, 0xf4, 0xa3, 0xa7, 0xec, 0x0a, 0xff, 0x07, 0x69, 0xd7, 0xe6, 0xd2,
	0xe3, 0x56, 0xda, 0xb5, 0xf5, 0x2a, 0x38, 0x9b, 0x80, 0x97, 0x7e, 0x4c, 0x90, 0xa5, 0x7c, 0x45,
	0xfa, 0x39, 0x1f, 0xe7, 0xe7, 0x38, 0xdb, 0x1c, 0x8f, 0x9c, 0x59, 0x92, 0xa9, 0xe7, 0x13, 0x9a,
	0xf4, 0x67, 0xf1, 0x3a, 0x0d, 0xb4, 0x24, 0x84, 0xf4, 0x71, 0x07, 0x4c, 0x08, 0xb5, 0x68, 0x30,
	0x63, 0x23, 0x1a, 0xe9, 0x51, 0xe1, 0x03, 0xf0, 0x5f, 0x40, 0xda, 0x38, 0xb0, 0x2b, 0xae, 0x67,
	0x93, 0xcd, 0x5c, 0x7a, 0x5e, 0x59, 0x9c, 0x34, 0x2f, 0x45, 0xa0, 0xef, 0x87, 0xf9, 0x33, 0x22,
	0x30, 0xa1, 0xbd, 0x6e, 0xb8, 0x14, 0x35, 0x30, 0xab, 0x19, 0x65, 0x8f, 0x1d, 0xec, 0x2e, 0x03,
	0x99, 0xa4, 0xb2, 0xc7, 0xac, 0x29, 0x21, 0x50, 0x8e, 0xf8, 0x91, 0x1e, 0xa3, 0x0c, 0xd7, 0x2b,
	0x6d, 0xe2, 0x3a, 0x35, 0x96, 0x1b, 0x3b, 0x81, 0x1e, 0x17, 0x78, 0xce, 0xf9, 0xfa, 0x5d, 0x30,
	0xcd, 0xe7, 0xf0, 0x8c, 0x32, 0x12, 0xf4, 0xce, 0xac, 0x04, 0x26, 0xb0, 0x6d, 0x07, 0x24, 0x14,
	0x99, 0x98, 0x34, 0x73, 0x07, 0xbb, 0xcb, 0x33, 0x52, 0x62, 0x55, 0x54, 0x9e, 0xb0, 0xc0, 0xf5,
	0x1c, 0xab, 0x07, 0xd4, 0xef, 0xcb, 0xcc, 0x49, 0x21, 0x39, 0xc4, 0x2b, 0x20, 0xd3, 0x8a, 0x16,
	0xe4, 0x59, 0xce, 0xc6, 0x8d, 0x90, 0x33, 0xe4, 0xdc, 0x04, 0xba, 0xf4, 0x21, 0x03, 0x32, 0x5c,
	0x0d, 0xbe, 0x51, 0x40, 0x56, 0x84, 0x0f, 0x2e, 0xc4, 0x91, 0x07, 0x73, 0xae, 0x5e, 0x1c, 0x8a,
	0x13, 0xe6, 0xf4, 0xc2, 0xab, 0xaf, 0x3f, 0xdf, 0xa7, 0x97, 0xe0, 0x22, 0xe2, 0x84, 0x65, 0x8f,
	0xb0, 0x36, 0x0d, 0xd6, 0x51, 0xe2, 0x2f, 0x09, 0xbf, 0x28, 0xe0, 0xd4, 0xf1, 0x13, 0x87, 0x85,
	0xc4, 0x7e, 0x09, 0xff, 0x84, 0x5a, 0x1c, 0x81, 0x21, 0xbd, 0xde, 0xe6, 0x5e, 0x6f, 0xc0, 0x6b,
	0xc3, 0xbd, 0xfe, 0xb9, 0x63, 0x2a, 0x22, 0x85, 0x68, 0xdb, 0xb5, 0x77, 0xe0, 0x67, 0x05, 0x4c,
	0x0f, 0xa4, 0x1d, 0xfe, 0xbb, 0x95, 0xfe, 0x7c, 0x4b, 0xa3, 0x50, 0xa4, 0xfd, 0x9b, 0xdc, 0xfe,
	0x55, 0x78, 0xf9, 0x04, 0xf6, 0x43, 0xf8, 0x4e, 0x01, 0x19, 0x9e, 0x12, 0x78, 0x21, 0xb1, 0xf7,
	0xd1, 0x00, 0xab, 0x0b, 0xc3, 0x60, 0xd2, 0xd6, 0x75, 0x6e, 0x6b, 0x05, 0x16, 0x87, 0xdb, 0xe2,
	0xc1, 0x44, 0xdb, 0x32, 0xee, 0x3b, 0xe6, 0xbd, 0xbd, 0x8e, 0xa6, 0xec, 0x77, 0x34, 0xe5, 0x47,
	0x47, 0x53, 0xde, 0x76, 0xb5, 0xd4, 0x7e, 0x57, 0x4b, 0x7d, 0xeb, 0x6a, 0xa9, 0x17, 0x05, 0xc7,
	0x65, 0xb5, 0xe6, 0x9a, 0x51, 0xa5, 0x8d, 0x58, 0xd9, 0xcd, 0x23, 0xc2, 0x6c, 0xcb, 0x27, 0xe1,
	0x5a, 0x96, 0x5f, 0xdb, 0x2b, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x54, 0x74, 0xfa, 0x94,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// AllocationOption queries a single allocation option by id.
	AllocationOption(ctx context.Context, in *QueryAllocationOptionRequest, opts ...grpc.CallOption) (*QueryAllocationOptionResponse, error)
	// AllocationOptions queries all allocation options.
	AllocationOptions(ctx context.Context, in *QueryAllocationOptionsRequest, opts ...grpc.CallOption) (*QueryAllocationOptionsResponse, error)
	// Voter queries a staker's allocation split.
	Voter(ctx context.Context, in *QueryVoterRequest, opts ...grpc.CallOption) (*QueryVoterResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/earth.deflation.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllocationOption(ctx context.Context, in *QueryAllocationOptionRequest, opts ...grpc.CallOption) (*QueryAllocationOptionResponse, error) {
	out := new(QueryAllocationOptionResponse)
	err := c.cc.Invoke(ctx, "/earth.deflation.v1.Query/AllocationOption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllocationOptions(ctx context.Context, in *QueryAllocationOptionsRequest, opts ...grpc.CallOption) (*QueryAllocationOptionsResponse, error) {
	out := new(QueryAllocationOptionsResponse)
	err := c.cc.Invoke(ctx, "/earth.deflation.v1.Query/AllocationOptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Voter(ctx context.Context, in *QueryVoterRequest, opts ...grpc.CallOption) (*QueryVoterResponse, error) {
	out := new(QueryVoterResponse)
	err := c.cc.Invoke(ctx, "/earth.deflation.v1.Query/Voter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// AllocationOption queries a single allocation option by id.
	AllocationOption(context.Context, *QueryAllocationOptionRequest) (*QueryAllocationOptionResponse, error)
	// AllocationOptions queries all allocation options.
	AllocationOptions(context.Context, *QueryAllocationOptionsRequest) (*QueryAllocationOptionsResponse, error)
	// Voter queries a staker's allocation split.
	Voter(context.Context, *QueryVoterRequest) (*QueryVoterResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AllocationOption(ctx context.Context, req *QueryAllocationOptionRequest) (*QueryAllocationOptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocationOption not implemented")
}
func (*UnimplementedQueryServer) AllocationOptions(ctx context.Context, req *QueryAllocationOptionsRequest) (*QueryAllocationOptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocationOptions not implemented")
}
func (*UnimplementedQueryServer) Voter(ctx context.Context, req *QueryVoterRequest) (*QueryVoterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Voter not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.deflation.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllocationOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllocationOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllocationOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.deflation.v1.Query/AllocationOption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllocationOption(ctx, req.(*QueryAllocationOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllocationOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllocationOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllocationOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.deflation.v1.Query/AllocationOptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllocationOptions(ctx, req.(*QueryAllocationOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Voter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVoterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Voter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.deflation.v1.Query/Voter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Voter(ctx, req.(*QueryVoterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "earth.deflation.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AllocationOption",
			Handler:    _Query_AllocationOption_Handler,
		},
		{
			MethodName: "AllocationOptions",
			Handler:    _Query_AllocationOptions_Handler,
		},
		{
			MethodName: "Voter",
			Handler:    _Query_Voter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "earth/deflation/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllocationOptionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllocationOptionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllocationOptionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllocationOptionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllocationOptionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllocationOptionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Option.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllocationOptionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllocationOptionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllocationOptionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAllocationOptionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllocationOptionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllocationOptionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalWeight.Size()
		i -= size
		if _, err := m.TotalWeight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.RewardIndex.Size()
		i -= size
		if _, err := m.RewardIndex.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Options) > 0 {
		for iNdEx := len(m.Options) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Options[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryVoterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVoterRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVoterRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVoterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVoterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVoterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Voter.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllocationOptionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryAllocationOptionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Option.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllocationOptionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAllocationOptionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Options) > 0 {
		for _, e := range m.Options {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	l = m.RewardIndex.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.TotalWeight.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryVoterRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVoterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Voter.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllocationOptionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllocationOptionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllocationOptionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllocationOptionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllocationOptionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllocationOptionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Option", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Option.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllocationOptionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllocationOptionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllocationOptionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllocationOptionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllocationOptionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllocationOptionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Options", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Options = append(m.Options, AllocationOption{})
			if err := m.Options[len(m.Options)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalWeight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalWeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVoterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVoterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVoterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVoterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVoterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVoterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Voter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
