// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: earth/personhood/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c227ef87cf4ce02e, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c227ef87cf4ce02e, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryRegistrationRequest requests a wallet's registration.
type QueryRegistrationRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryRegistrationRequest) Reset()         { *m = QueryRegistrationRequest{} }
func (m *QueryRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRegistrationRequest) ProtoMessage()    {}
func (*QueryRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c227ef87cf4ce02e, []int{2}
}
func (m *QueryRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistrationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistrationRequest.Merge(m, src)
}
func (m *QueryRegistrationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistrationRequest proto.InternalMessageInfo

func (m *QueryRegistrationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryRegistrationResponse returns a wallet's registration status.
type QueryRegistrationResponse struct {
	Registered   bool         `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"`
	Expired      bool         `protobuf:"varint,2,opt,name=expired,proto3" json:"expired,omitempty"`
	Registration Registration `protobuf:"bytes,3,opt,name=registration,proto3" json:"registration"`
}

func (m *QueryRegistrationResponse) Reset()         { *m = QueryRegistrationResponse{} }
func (m *QueryRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRegistrationResponse) ProtoMessage()    {}
func (*QueryRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c227ef87cf4ce02e, []int{3}
}
func (m *QueryRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistrationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistrationResponse.Merge(m, src)
}
func (m *QueryRegistrationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistrationResponse proto.InternalMessageInfo

func (m *QueryRegistrationResponse) GetRegistered() bool {
	if m != nil {
		return m.Registered
	}
	return false
}

func (m *QueryRegistrationResponse) GetExpired() bool {
	if m != nil {
		return m.Expired
	}
	return false
}

func (m *QueryRegistrationResponse) GetRegistration() Registration {
	if m != nil {
		return m.Registration
	}
	return Registration{}
}

// QueryRegistrationCountRequest requests the live registration headcount.
type QueryRegistrationCountRequest struct {
}

func (m *QueryRegistrationCountRequest) Reset()         { *m = QueryRegistrationCountRequest{} }
func (m *QueryRegistrationCountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRegistrationCountRequest) ProtoMessage()    {}
func (*QueryRegistrationCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c227ef87cf4ce02e, []int{4}
}
func (m *QueryRegistrationCountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistrationCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistrationCountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistrationCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistrationCountRequest.Merge(m, src)
}
func (m *QueryRegistrationCountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistrationCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistrationCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistrationCountRequest proto.InternalMessageInfo

// QueryRegistrationCountResponse returns the live registration headcount. This
// is the denominator of the human emission stream: one vote each.
type QueryRegistrationCountResponse struct {
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *QueryRegistrationCountResponse) Reset()         { *m = QueryRegistrationCountResponse{} }
func (m *QueryRegistrationCountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRegistrationCountResponse) ProtoMessage()    {}
func (*QueryRegistrationCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c227ef87cf4ce02e, []int{5}
}
func (m *QueryRegistrationCountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistrationCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistrationCountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistrationCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistrationCountResponse.Merge(m, src)
}
func (m *QueryRegistrationCountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistrationCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistrationCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistrationCountResponse proto.InternalMessageInfo

func (m *QueryRegistrationCountResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// QueryRegistrationsByDscRequest identifies a Document Signer by the hex-encoded
// dsc_key commitment recorded on its registrations.
type QueryRegistrationsByDscRequest struct {
	DscKey string `protobuf:"bytes,1,opt,name=dsc_key,json=dscKey,proto3" json:"dsc_key,omitempty"`
}

func (m *QueryRegistrationsByDscRequest) Reset()         { *m = QueryRegistrationsByDscRequest{} }
func (m *QueryRegistrationsByDscRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRegistrationsByDscRequest) ProtoMessage()    {}
func (*QueryRegistrationsByDscRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c227ef87cf4ce02e, []int{6}
}
func (m *QueryRegistrationsByDscRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistrationsByDscRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistrationsByDscRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistrationsByDscRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistrationsByDscRequest.Merge(m, src)
}
func (m *QueryRegistrationsByDscRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistrationsByDscRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistrationsByDscRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistrationsByDscRequest proto.InternalMessageInfo

func (m *QueryRegistrationsByDscRequest) GetDscKey() string {
	if m != nil {
		return m.DscKey
	}
	return ""
}

type QueryRegistrationsByDscResponse struct {
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *QueryRegistrationsByDscResponse) Reset()         { *m = QueryRegistrationsByDscResponse{} }
func (m *QueryRegistrationsByDscResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRegistrationsByDscResponse) ProtoMessage()    {}
func (*QueryRegistrationsByDscResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c227ef87cf4ce02e, []int{7}
}
func (m *QueryRegistrationsByDscResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistrationsByDscResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistrationsByDscResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistrationsByDscResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistrationsByDscResponse.Merge(m, src)
}
func (m *QueryRegistrationsByDscResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistrationsByDscResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistrationsByDscResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistrationsByDscResponse proto.InternalMessageInfo

func (m *QueryRegistrationsByDscResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// CountryCount is one country's registration total.
type CountryCount struct {
	Country string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Count   uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *CountryCount) Reset()         { *m = CountryCount{} }
func (m *CountryCount) String() string { return proto.CompactTextString(m) }
func (*CountryCount) ProtoMessage()    {}
func (*CountryCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c227ef87cf4ce02e, []int{8}
}
func (m *CountryCount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CountryCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CountryCount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CountryCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountryCount.Merge(m, src)
}
func (m *CountryCount) XXX_Size() int {
	return m.Size()
}
func (m *CountryCount) XXX_DiscardUnknown() {
	xxx_messageInfo_CountryCount.DiscardUnknown(m)
}

var xxx_messageInfo_CountryCount proto.InternalMessageInfo

func (m *CountryCount) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CountryCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type QueryRegistrationCountriesRequest struct {
}

func (m *QueryRegistrationCountriesRequest) Reset()         { *m = QueryRegistrationCountriesRequest{} }
func (m *QueryRegistrationCountriesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRegistrationCountriesRequest) ProtoMessage()    {}
func (*QueryRegistrationCountriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c227ef87cf4ce02e, []int{9}
}
func (m *QueryRegistrationCountriesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistrationCountriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistrationCountriesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistrationCountriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistrationCountriesRequest.Merge(m, src)
}
func (m *QueryRegistrationCountriesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistrationCountriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistrationCountriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistrationCountriesRequest proto.InternalMessageInfo

type QueryRegistrationCountriesResponse struct {
	Countries []CountryCount `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries"`
}

func (m *QueryRegistrationCountriesResponse) Reset()         { *m = QueryRegistrationCountriesResponse{} }
func (m *QueryRegistrationCountriesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRegistrationCountriesResponse) ProtoMessage()    {}
func (*QueryRegistrationCountriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c227ef87cf4ce02e, []int{10}
}
func (m *QueryRegistrationCountriesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistrationCountriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistrationCountriesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistrationCountriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistrationCountriesResponse.Merge(m, src)
}
func (m *QueryRegistrationCountriesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistrationCountriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistrationCountriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistrationCountriesResponse proto.InternalMessageInfo

func (m *QueryRegistrationCountriesResponse) GetCountries() []CountryCount {
	if m != nil {
		return m.Countries
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "earth.personhood.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "earth.personhood.v1.QueryParamsResponse")
	proto.RegisterType((*QueryRegistrationRequest)(nil), "earth.personhood.v1.QueryRegistrationRequest")
	proto.RegisterType((*QueryRegistrationResponse)(nil), "earth.personhood.v1.QueryRegistrationResponse")
	proto.RegisterType((*QueryRegistrationCountRequest)(nil), "earth.personhood.v1.QueryRegistrationCountRequest")
	proto.RegisterType((*QueryRegistrationCountResponse)(nil), "earth.personhood.v1.QueryRegistrationCountResponse")
	proto.RegisterType((*QueryRegistrationsByDscRequest)(nil), "earth.personhood.v1.QueryRegistrationsByDscRequest")
	proto.RegisterType((*QueryRegistrationsByDscResponse)(nil), "earth.personhood.v1.QueryRegistrationsByDscResponse")
	proto.RegisterType((*CountryCount)(nil), "earth.personhood.v1.CountryCount")
	proto.RegisterType((*QueryRegistrationCountriesRequest)(nil), "earth.personhood.v1.QueryRegistrationCountriesRequest")
	proto.RegisterType((*QueryRegistrationCountriesResponse)(nil), "earth.personhood.v1.QueryRegistrationCountriesResponse")
}

func init() { proto.RegisterFile("earth/personhood/v1/query.proto", fileDescriptor_c227ef87cf4ce02e) }

var fileDescriptor_c227ef87cf4ce02e = []byte{
	// 709 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4f, 0x4f, 0x13, 0x41,
	0x1c, 0xed, 0xf2, 0xa7, 0x95, 0x9f, 0x5c, 0x18, 0x6a, 0x2c, 0x55, 0xb7, 0xb0, 0x26, 0x8a, 0x18,
	0x76, 0xd2, 0xa2, 0x10, 0x62, 0x24, 0xa1, 0xe8, 0xc1, 0x90, 0x18, 0x5d, 0xe3, 0xc5, 0x4b, 0xb3,
	0xdd, 0x9d, 0x2c, 0x1b, 0xec, 0xce, 0x32, 0xb3, 0x45, 0x36, 0x84, 0x8b, 0x1f, 0xc0, 0x98, 0xf8,
	0x0d, 0x8c, 0x07, 0x8f, 0x1c, 0xbc, 0xf9, 0x05, 0x88, 0x5e, 0x88, 0x5e, 0x3c, 0x19, 0x03, 0x26,
	0x7e, 0x0d, 0xd3, 0x99, 0x59, 0x58, 0xd2, 0x2d, 0xb6, 0xf1, 0xd2, 0x76, 0x66, 0xde, 0xfb, 0xfd,
	0xde, 0xfb, 0xcd, 0xbc, 0x14, 0x2a, 0xc4, 0x66, 0xd1, 0x06, 0x0e, 0x09, 0xe3, 0x34, 0xd8, 0xa0,
	0xd4, 0xc5, 0xdb, 0x55, 0xbc, 0xd5, 0x26, 0x2c, 0x36, 0x43, 0x46, 0x23, 0x8a, 0x26, 0x05, 0xc0,
	0x3c, 0x05, 0x98, 0xdb, 0xd5, 0xf2, 0x84, 0xdd, 0xf2, 0x03, 0x8a, 0xc5, 0xa7, 0xc4, 0x95, 0xe7,
	0x1c, 0xca, 0x5b, 0x94, 0xe3, 0xa6, 0xcd, 0x89, 0x2c, 0x80, 0xb7, 0xab, 0x4d, 0x12, 0xd9, 0x55,
	0x1c, 0xda, 0x9e, 0x1f, 0xd8, 0x91, 0x4f, 0x03, 0x85, 0x9d, 0x92, 0xd8, 0x86, 0x58, 0x61, 0xb9,
	0x50, 0x47, 0xd3, 0x59, 0x7a, 0x42, 0x9b, 0xd9, 0xad, 0x04, 0x71, 0x23, 0x0b, 0xc1, 0x88, 0xe7,
	0xf3, 0x88, 0xa5, 0x9b, 0x14, 0x3d, 0xea, 0x51, 0xd9, 0xa1, 0xf3, 0x4b, 0xed, 0x5e, 0xf5, 0x28,
	0xf5, 0x5e, 0x12, 0x6c, 0x87, 0x3e, 0xb6, 0x83, 0x80, 0x46, 0x82, 0xa2, 0x6a, 0x1b, 0x45, 0x40,
	0x4f, 0x3b, 0xd2, 0x9f, 0x88, 0x86, 0x16, 0xd9, 0x6a, 0x13, 0x1e, 0x19, 0xcf, 0x61, 0xf2, 0xcc,
	0x2e, 0x0f, 0x69, 0xc0, 0x09, 0x5a, 0x81, 0xbc, 0x14, 0x56, 0xd2, 0xa6, 0xb5, 0xd9, 0x8b, 0xb5,
	0x2b, 0x66, 0xc6, 0xa8, 0x4c, 0x49, 0xaa, 0x8f, 0x1d, 0xfc, 0xac, 0xe4, 0x3e, 0xfe, 0xd9, 0x9f,
	0xd3, 0x2c, 0xc5, 0x32, 0x1e, 0x43, 0x49, 0x94, 0xb5, 0x52, 0xda, 0x55, 0x4b, 0x54, 0x83, 0x82,
	0xed, 0xba, 0x8c, 0x70, 0x59, 0x7c, 0xac, 0x5e, 0xfa, 0xf6, 0x69, 0xbe, 0xa8, 0x26, 0xb5, 0x2a,
	0x4f, 0x9e, 0x45, 0xcc, 0x0f, 0x3c, 0x2b, 0x01, 0x1a, 0xef, 0x35, 0x98, 0xca, 0x28, 0xa8, 0xd4,
	0xea, 0x00, 0x72, 0x48, 0x84, 0x11, 0x57, 0x14, 0xbd, 0x60, 0xa5, 0x76, 0x50, 0x09, 0x0a, 0x64,
	0x27, 0xf4, 0x3b, 0x87, 0x43, 0xe2, 0x30, 0x59, 0xa2, 0x75, 0x18, 0x4f, 0x8f, 0xb7, 0x34, 0x2c,
	0xdc, 0xce, 0x64, 0xba, 0x4d, 0xb7, 0xae, 0x8f, 0x74, 0x3c, 0x5b, 0x67, 0xc8, 0x46, 0x05, 0xae,
	0x75, 0x69, 0x5c, 0xa3, 0xed, 0x20, 0x4a, 0x86, 0xbd, 0x08, 0x7a, 0x2f, 0x80, 0x72, 0x52, 0x84,
	0x51, 0xa7, 0xb3, 0x21, 0x4c, 0x8c, 0x58, 0x72, 0x61, 0x2c, 0x67, 0xf0, 0x78, 0x3d, 0x7e, 0xc0,
	0x9d, 0x64, 0xa6, 0x97, 0xa1, 0xe0, 0x72, 0xa7, 0xb1, 0x49, 0x62, 0x39, 0x53, 0x2b, 0xef, 0x72,
	0x67, 0x9d, 0xc4, 0xc6, 0x12, 0x54, 0x7a, 0x52, 0xcf, 0xed, 0xb9, 0x02, 0xe3, 0x42, 0x1a, 0x8b,
	0xc5, 0x57, 0x67, 0x86, 0x8e, 0x5c, 0xab, 0x0e, 0xc9, 0xf2, 0x94, 0x3f, 0x94, 0xe6, 0x5f, 0x87,
	0x99, 0x6c, 0xaf, 0xcc, 0x27, 0x27, 0xaf, 0x6f, 0x13, 0x8c, 0xf3, 0x40, 0x4a, 0xe0, 0x43, 0x18,
	0x73, 0x92, 0xcd, 0x92, 0x36, 0x3d, 0xdc, 0xf3, 0x86, 0xd2, 0x82, 0xd5, 0x0d, 0x9d, 0x32, 0x6b,
	0x1f, 0x0a, 0x30, 0x2a, 0xba, 0xa1, 0x37, 0x1a, 0xe4, 0xe5, 0xdb, 0x45, 0x37, 0x33, 0x0b, 0x75,
	0x07, 0xa5, 0x3c, 0xfb, 0x6f, 0xa0, 0x94, 0x6b, 0x54, 0x5f, 0x7f, 0xff, 0xfd, 0x6e, 0xe8, 0x36,
	0xba, 0x85, 0x05, 0x63, 0x3e, 0x20, 0xd1, 0x2b, 0xca, 0x36, 0x71, 0xef, 0xf4, 0xa3, 0x7d, 0x0d,
	0xc6, 0xd3, 0x33, 0x40, 0xf3, 0xbd, 0xbb, 0x65, 0x44, 0xaa, 0x6c, 0xf6, 0x0b, 0x57, 0x12, 0x57,
	0x85, 0xc4, 0x7b, 0x68, 0xb9, 0x0f, 0x89, 0xe9, 0x27, 0x8e, 0x77, 0x55, 0x20, 0xf7, 0xd0, 0x67,
	0x0d, 0x26, 0xba, 0xae, 0x0d, 0xd5, 0xfa, 0x13, 0x92, 0x4e, 0x45, 0x79, 0x61, 0x20, 0x8e, 0x72,
	0x70, 0x5f, 0x38, 0x58, 0x42, 0x77, 0x07, 0x74, 0xd0, 0x10, 0xef, 0x01, 0x7d, 0xd1, 0x00, 0x75,
	0x47, 0x02, 0xf5, 0x29, 0xe5, 0x4c, 0xf6, 0xca, 0x77, 0x06, 0x23, 0x29, 0x03, 0x8f, 0x84, 0x81,
	0x35, 0xb4, 0x3a, 0xa0, 0x01, 0xde, 0x68, 0xc6, 0x0d, 0x97, 0x3b, 0x78, 0x57, 0x05, 0x7e, 0x0f,
	0x7d, 0xd5, 0xe0, 0x52, 0x66, 0x82, 0xd0, 0xe2, 0x00, 0xa3, 0x4d, 0xe5, 0xb2, 0xbc, 0x34, 0x30,
	0xef, 0x3f, 0x1f, 0x56, 0xe3, 0x24, 0xa6, 0xf5, 0xf5, 0x83, 0x23, 0x5d, 0x3b, 0x3c, 0xd2, 0xb5,
	0x5f, 0x47, 0xba, 0xf6, 0xf6, 0x58, 0xcf, 0x1d, 0x1e, 0xeb, 0xb9, 0x1f, 0xc7, 0x7a, 0xee, 0x45,
	0xd5, 0xf3, 0xa3, 0x8d, 0x76, 0xd3, 0x74, 0x68, 0x2b, 0xb3, 0xfc, 0x4e, 0xba, 0x41, 0x14, 0x87,
	0x84, 0x37, 0xf3, 0xe2, 0xbf, 0x6f, 0xe1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0x05, 0x05,
	0x44, 0x0b, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Registration queries a wallet's registration status.
	Registration(ctx context.Context, in *QueryRegistrationRequest, opts ...grpc.CallOption) (*QueryRegistrationResponse, error)
	// RegistrationCount returns how many humans are currently registered.
	RegistrationCount(ctx context.Context, in *QueryRegistrationCountRequest, opts ...grpc.CallOption) (*QueryRegistrationCountResponse, error)
	// RegistrationsByDsc counts registrations produced by one Document Signer.
	RegistrationsByDsc(ctx context.Context, in *QueryRegistrationsByDscRequest, opts ...grpc.CallOption) (*QueryRegistrationsByDscResponse, error)
	// RegistrationCountries returns the registration count per issuing country.
	RegistrationCountries(ctx context.Context, in *QueryRegistrationCountriesRequest, opts ...grpc.CallOption) (*QueryRegistrationCountriesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/earth.personhood.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Registration(ctx context.Context, in *QueryRegistrationRequest, opts ...grpc.CallOption) (*QueryRegistrationResponse, error) {
	out := new(QueryRegistrationResponse)
	err := c.cc.Invoke(ctx, "/earth.personhood.v1.Query/Registration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegistrationCount(ctx context.Context, in *QueryRegistrationCountRequest, opts ...grpc.CallOption) (*QueryRegistrationCountResponse, error) {
	out := new(QueryRegistrationCountResponse)
	err := c.cc.Invoke(ctx, "/earth.personhood.v1.Query/RegistrationCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegistrationsByDsc(ctx context.Context, in *QueryRegistrationsByDscRequest, opts ...grpc.CallOption) (*QueryRegistrationsByDscResponse, error) {
	out := new(QueryRegistrationsByDscResponse)
	err := c.cc.Invoke(ctx, "/earth.personhood.v1.Query/RegistrationsByDsc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegistrationCountries(ctx context.Context, in *QueryRegistrationCountriesRequest, opts ...grpc.CallOption) (*QueryRegistrationCountriesResponse, error) {
	out := new(QueryRegistrationCountriesResponse)
	err := c.cc.Invoke(ctx, "/earth.personhood.v1.Query/RegistrationCountries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Registration queries a wallet's registration status.
	Registration(context.Context, *QueryRegistrationRequest) (*QueryRegistrationResponse, error)
	// RegistrationCount returns how many humans are currently registered.
	RegistrationCount(context.Context, *QueryRegistrationCountRequest) (*QueryRegistrationCountResponse, error)
	// RegistrationsByDsc counts registrations produced by one Document Signer.
	RegistrationsByDsc(context.Context, *QueryRegistrationsByDscRequest) (*QueryRegistrationsByDscResponse, error)
	// RegistrationCountries returns the registration count per issuing country.
	RegistrationCountries(context.Context, *QueryRegistrationCountriesRequest) (*QueryRegistrationCountriesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Registration(ctx context.Context, req *QueryRegistrationRequest) (*QueryRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registration not implemented")
}
func (*UnimplementedQueryServer) RegistrationCount(ctx context.Context, req *QueryRegistrationCountRequest) (*QueryRegistrationCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistrationCount not implemented")
}
func (*UnimplementedQueryServer) RegistrationsByDsc(ctx context.Context, req *QueryRegistrationsByDscRequest) (*QueryRegistrationsByDscResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistrationsByDsc not implemented")
}
func (*UnimplementedQueryServer) RegistrationCountries(ctx context.Context, req *QueryRegistrationCountriesRequest) (*QueryRegistrationCountriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistrationCountries not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.personhood.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Registration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Registration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.personhood.v1.Query/Registration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Registration(ctx, req.(*QueryRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegistrationCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegistrationCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegistrationCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.personhood.v1.Query/RegistrationCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegistrationCount(ctx, req.(*QueryRegistrationCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegistrationsByDsc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegistrationsByDscRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegistrationsByDsc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.personhood.v1.Query/RegistrationsByDsc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegistrationsByDsc(ctx, req.(*QueryRegistrationsByDscRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegistrationCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegistrationCountriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegistrationCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.personhood.v1.Query/RegistrationCountries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegistrationCountries(ctx, req.(*QueryRegistrationCountriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "earth.personhood.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Registration",
			Handler:    _Query_Registration_Handler,
		},
		{
			MethodName: "RegistrationCount",
			Handler:    _Query_RegistrationCount_Handler,
		},
		{
			MethodName: "RegistrationsByDsc",
			Handler:    _Query_RegistrationsByDsc_Handler,
		},
		{
			MethodName: "RegistrationCountries",
			Handler:    _Query_RegistrationCountries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "earth/personhood/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRegistrationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistrationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistrationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegistrationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistrationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistrationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Registration.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Expired {
		i--
		if m.Expired {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Registered {
		i--
		if m.Registered {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegistrationCountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistrationCountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistrationCountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryRegistrationCountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistrationCountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistrationCountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegistrationsByDscRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistrationsByDscRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistrationsByDscRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DscKey) > 0 {
		i -= len(m.DscKey)
		copy(dAtA[i:], m.DscKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DscKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegistrationsByDscResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistrationsByDscResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistrationsByDscResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CountryCount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CountryCount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CountryCount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Country) > 0 {
		i -= len(m.Country)
		copy(dAtA[i:], m.Country)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Country)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegistrationCountriesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistrationCountriesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistrationCountriesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryRegistrationCountriesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistrationCountriesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistrationCountriesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Countries) > 0 {
		for iNdEx := len(m.Countries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Countries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRegistrationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRegistrationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Registered {
		n += 2
	}
	if m.Expired {
		n += 2
	}
	l = m.Registration.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRegistrationCountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryRegistrationCountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovQuery(uint64(m.Count))
	}
	return n
}

func (m *QueryRegistrationsByDscRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DscKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRegistrationsByDscResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovQuery(uint64(m.Count))
	}
	return n
}

func (m *CountryCount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Country)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Count != 0 {
		n += 1 + sovQuery(uint64(m.Count))
	}
	return n
}

func (m *QueryRegistrationCountriesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryRegistrationCountriesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Countries) > 0 {
		for _, e := range m.Countries {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistrationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistrationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistrationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistrationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistrationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistrationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registered", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Registered = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expired", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Expired = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Registration.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistrationCountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistrationCountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistrationCountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistrationCountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistrationCountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistrationCountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistrationsByDscRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistrationsByDscRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistrationsByDscRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DscKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DscKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistrationsByDscResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistrationsByDscResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistrationsByDscResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CountryCount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CountryCount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CountryCount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Country", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Country = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistrationCountriesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistrationCountriesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistrationCountriesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistrationCountriesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistrationCountriesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistrationCountriesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Countries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Countries = append(m.Countries, CountryCount{})
			if err := m.Countries[len(m.Countries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
