// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: earth/personhood/v1/registration.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Registration is a proof-of-personhood record: one unique human, deduped by the
// zk nullifier, bound to a wallet address.
type Registration struct {
	// nullifier is the unique per-person value output by the registration proof.
	Nullifier []byte `protobuf:"bytes,1,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	// address is the registered wallet.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// registered_at is the unix time (seconds) of registration.
	RegisteredAt int64 `protobuf:"varint,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	// last_anml_claim is the unix time (seconds, UTC midnight) of the last ANML claim.
	LastAnmlClaim int64 `protobuf:"varint,4,opt,name=last_anml_claim,json=lastAnmlClaim,proto3" json:"last_anml_claim,omitempty"`
	// dsc_key is the Poseidon2 commitment to the Document Signer that produced the
	// registration proof — the same value the circuit exposed publicly. Recording
	// it is what makes a compromised signer's registrations enumerable.
	DscKey []byte `protobuf:"bytes,5,opt,name=dsc_key,json=dscKey,proto3" json:"dsc_key,omitempty"`
	// country is the DSC's ISO 3166-1 alpha-2 issuing country, or "" when the
	// certificate carries no country attribute.
	Country string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
}

func (m *Registration) Reset()         { *m = Registration{} }
func (m *Registration) String() string { return proto.CompactTextString(m) }
func (*Registration) ProtoMessage()    {}
func (*Registration) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6481390e9f75f57, []int{0}
}
func (m *Registration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Registration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Registration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Registration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Registration.Merge(m, src)
}
func (m *Registration) XXX_Size() int {
	return m.Size()
}
func (m *Registration) XXX_DiscardUnknown() {
	xxx_messageInfo_Registration.DiscardUnknown(m)
}

var xxx_messageInfo_Registration proto.InternalMessageInfo

func (m *Registration) GetNullifier() []byte {
	if m != nil {
		return m.Nullifier
	}
	return nil
}

func (m *Registration) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Registration) GetRegisteredAt() int64 {
	if m != nil {
		return m.RegisteredAt
	}
	return 0
}

func (m *Registration) GetLastAnmlClaim() int64 {
	if m != nil {
		return m.LastAnmlClaim
	}
	return 0
}

func (m *Registration) GetDscKey() []byte {
	if m != nil {
		return m.DscKey
	}
	return nil
}

func (m *Registration) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

// RateCounter is a self-resetting daily counter, used to bound how many
// registrations one Document Signer or one issuing country may produce in a day.
//
// Stored as a (day, count) pair rather than as a row per day so it costs one
// entry per subject no matter how long the chain runs: when the day rolls the
// count resets in place, and there is nothing to prune. The cost of that is
// that history is not kept — only the current day, and the one before it.
type RateCounter struct {
	// day is the unix day (block time / 86400) the count belongs to.
	Day uint64 `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	// count is how many registrations have landed during that day.
	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// previous_count is the completed previous day's total.
	//
	// Only the network-wide counter uses it, and it is what the per-signer caps
	// scale against. Scaling against the current day instead would be circular:
	// the day starts at zero, so every cap would start the day at its floor and
	// widen as registrations arrived — tightest exactly when a burst begins.
	PreviousCount uint64 `protobuf:"varint,3,opt,name=previous_count,json=previousCount,proto3" json:"previous_count,omitempty"`
}

func (m *RateCounter) Reset()         { *m = RateCounter{} }
func (m *RateCounter) String() string { return proto.CompactTextString(m) }
func (*RateCounter) ProtoMessage()    {}
func (*RateCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6481390e9f75f57, []int{1}
}
func (m *RateCounter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RateCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RateCounter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RateCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateCounter.Merge(m, src)
}
func (m *RateCounter) XXX_Size() int {
	return m.Size()
}
func (m *RateCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_RateCounter.DiscardUnknown(m)
}

var xxx_messageInfo_RateCounter proto.InternalMessageInfo

func (m *RateCounter) GetDay() uint64 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *RateCounter) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *RateCounter) GetPreviousCount() uint64 {
	if m != nil {
		return m.PreviousCount
	}
	return 0
}

func init() {
	proto.RegisterType((*Registration)(nil), "earth.personhood.v1.Registration")
	proto.RegisterType((*RateCounter)(nil), "earth.personhood.v1.RateCounter")
}

func init() {
	proto.RegisterFile("earth/personhood/v1/registration.proto", fileDescriptor_b6481390e9f75f57)
}

var fileDescriptor_b6481390e9f75f57 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xdf, 0x4e, 0xfa, 0x30,
	0x1c, 0xc5, 0xe9, 0x6f, 0xfc, 0x09, 0xfd, 0x81, 0x9a, 0x4a, 0x62, 0x35, 0x66, 0x21, 0x18, 0x09,
	0x37, 0x6c, 0x41, 0x9f, 0x00, 0xb8, 0xe4, 0xae, 0xde, 0x19, 0x93, 0xa5, 0x6c, 0x15, 0x1a, 0xb6,
	0x76, 0x69, 0x3b, 0x74, 0x6f, 0xe1, 0xc3, 0xf8, 0x10, 0x5e, 0x12, 0xaf, 0xbc, 0x24, 0xf0, 0x22,
	0x66, 0x9d, 0x04, 0xee, 0x7a, 0xce, 0xf7, 0x93, 0x93, 0xd3, 0x1c, 0xd8, 0x67, 0x54, 0x99, 0xa5,
	0x9f, 0x32, 0xa5, 0xa5, 0x58, 0x4a, 0x19, 0xf9, 0xeb, 0x91, 0xaf, 0xd8, 0x82, 0x6b, 0xa3, 0xa8,
	0xe1, 0x52, 0x78, 0xa9, 0x92, 0x46, 0xa2, 0x4b, 0xcb, 0x79, 0x47, 0xce, 0x5b, 0x8f, 0x6e, 0xae,
	0x43, 0xa9, 0x13, 0xa9, 0x03, 0x8b, 0xf8, 0xa5, 0x28, 0xf9, 0xde, 0x16, 0xc0, 0x16, 0x39, 0x89,
	0x41, 0xb7, 0xb0, 0x29, 0xb2, 0x38, 0xe6, 0xaf, 0x9c, 0x29, 0x0c, 0xba, 0x60, 0xd0, 0x22, 0x47,
	0x03, 0x3d, 0xc0, 0x06, 0x8d, 0x22, 0xc5, 0xb4, 0xc6, 0xff, 0xba, 0x60, 0xd0, 0x9c, 0xe0, 0xef,
	0xcf, 0x61, 0xe7, 0x2f, 0x71, 0x5c, 0x5e, 0x9e, 0x8c, 0xe2, 0x62, 0x41, 0x0e, 0x20, 0xba, 0x83,
	0xed, 0xb2, 0x28, 0x53, 0x2c, 0x0a, 0xa8, 0xc1, 0x4e, 0x17, 0x0c, 0x1c, 0xd2, 0x3a, 0x9a, 0x63,
	0x83, 0xfa, 0xf0, 0x3c, 0xa6, 0xda, 0x04, 0x54, 0x24, 0x71, 0x10, 0xc6, 0x94, 0x27, 0xb8, 0x6a,
	0xb1, 0x76, 0x61, 0x8f, 0x45, 0x12, 0x4f, 0x0b, 0x13, 0x5d, 0xc1, 0x46, 0xa4, 0xc3, 0x60, 0xc5,
	0x72, 0x5c, 0xb3, 0xe5, 0xea, 0x91, 0x0e, 0x67, 0x2c, 0x47, 0x18, 0x36, 0x42, 0x99, 0x09, 0xa3,
	0x72, 0x5c, 0x2f, 0x9a, 0x91, 0x83, 0xec, 0xbd, 0xc0, 0xff, 0x84, 0x1a, 0x36, 0x2d, 0x24, 0x53,
	0xe8, 0x02, 0x3a, 0x11, 0xcd, 0xed, 0xd7, 0xaa, 0xa4, 0x78, 0xa2, 0x0e, 0xac, 0x59, 0xd6, 0x7e,
	0xa9, 0x4a, 0x4a, 0x81, 0xee, 0xe1, 0x59, 0xaa, 0xd8, 0x9a, 0xcb, 0x4c, 0x07, 0xe5, 0xd9, 0xb1,
	0xe7, 0xf6, 0xc1, 0xb5, 0x81, 0x93, 0xd9, 0xd7, 0xce, 0x05, 0x9b, 0x9d, 0x0b, 0xb6, 0x3b, 0x17,
	0x7c, 0xec, 0xdd, 0xca, 0x66, 0xef, 0x56, 0x7e, 0xf6, 0x6e, 0xe5, 0x79, 0xb4, 0xe0, 0x66, 0x99,
	0xcd, 0xbd, 0x50, 0x26, 0xbe, 0x5d, 0x65, 0x28, 0x98, 0x79, 0x93, 0x6a, 0x55, 0x2a, 0xff, 0xfd,
	0x74, 0x4d, 0x93, 0xa7, 0x4c, 0xcf, 0xeb, 0x76, 0x94, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xe2, 0xcc, 0x06, 0xec, 0xee, 0x01, 0x00, 0x00,
}

func (m *Registration) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Registration) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Registration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Country) > 0 {
		i -= len(m.Country)
		copy(dAtA[i:], m.Country)
		i = encodeVarintRegistration(dAtA, i, uint64(len(m.Country)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DscKey) > 0 {
		i -= len(m.DscKey)
		copy(dAtA[i:], m.DscKey)
		i = encodeVarintRegistration(dAtA, i, uint64(len(m.DscKey)))
		i--
		dAtA[i] = 0x2a
	}
	if m.LastAnmlClaim != 0 {
		i = encodeVarintRegistration(dAtA, i, uint64(m.LastAnmlClaim))
		i--
		dAtA[i] = 0x20
	}
	if m.RegisteredAt != 0 {
		i = encodeVarintRegistration(dAtA, i, uint64(m.RegisteredAt))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintRegistration(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintRegistration(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RateCounter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RateCounter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RateCounter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PreviousCount != 0 {
		i = encodeVarintRegistration(dAtA, i, uint64(m.PreviousCount))
		i--
		dAtA[i] = 0x18
	}
	if m.Count != 0 {
		i = encodeVarintRegistration(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if m.Day != 0 {
		i = encodeVarintRegistration(dAtA, i, uint64(m.Day))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintRegistration(dAtA []byte, offset int, v uint64) int {
	offset -= sovRegistration(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Registration) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovRegistration(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovRegistration(uint64(l))
	}
	if m.RegisteredAt != 0 {
		n += 1 + sovRegistration(uint64(m.RegisteredAt))
	}
	if m.LastAnmlClaim != 0 {
		n += 1 + sovRegistration(uint64(m.LastAnmlClaim))
	}
	l = len(m.DscKey)
	if l > 0 {
		n += 1 + l + sovRegistration(uint64(l))
	}
	l = len(m.Country)
	if l > 0 {
		n += 1 + l + sovRegistration(uint64(l))
	}
	return n
}

func (m *RateCounter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Day != 0 {
		n += 1 + sovRegistration(uint64(m.Day))
	}
	if m.Count != 0 {
		n += 1 + sovRegistration(uint64(m.Count))
	}
	if m.PreviousCount != 0 {
		n += 1 + sovRegistration(uint64(m.PreviousCount))
	}
	return n
}

func sovRegistration(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRegistration(x uint64) (n int) {
	return sovRegistration(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Registration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegistration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Registration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Registration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRegistration
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = append(m.Nullifier[:0], dAtA[iNdEx:postIndex]...)
			if m.Nullifier == nil {
				m.Nullifier = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAt", wireType)
			}
			m.RegisteredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisteredAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastAnmlClaim", wireType)
			}
			m.LastAnmlClaim = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastAnmlClaim |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DscKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRegistration
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DscKey = append(m.DscKey[:0], dAtA[iNdEx:postIndex]...)
			if m.DscKey == nil {
				m.DscKey = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Country", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Country = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRegistration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegistration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RateCounter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegistration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RateCounter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RateCounter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Day", wireType)
			}
			m.Day = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Day |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousCount", wireType)
			}
			m.PreviousCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreviousCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRegistration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegistration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRegistration(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRegistration
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRegistration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRegistration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRegistration
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRegistration
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRegistration
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRegistration        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRegistration          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRegistration = fmt.Errorf("proto: unexpected end of group")
)
