// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: earth/personhood/v1/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types1 "github.com/earth-network/earth/x/allocation/types"
	types "github.com/earth-network/earth/x/shielded/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_83fe5bb40ec19165, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83fe5bb40ec19165, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgRegister registers a passport. Private: unsigned, its fee paid by fee.
//
// proof is a passport circuit's UltraHonk proof and public_signals its public
// inputs as decimal strings (positions are params). The chain verifies it,
// verifies dsc_der against the CSCA trust store and binds it to the proof's
// dsc_key, pins current_date to block time, dedups on the passport nullifier,
// and requires the proof's `address` input to equal
// zk/privacy.RegistrationBinding =
//
//	H(TAG_REG, Bytes(chain_id), idc, pc_anml, Bytes(ciphertext_anml), pc_erth,
//	  Bytes(ciphertext_erth), affiliate)
//
// with affiliate = 0 when the registration names no referrer, and
//
//	H(TAG_AFFILIATE, Bytes(affiliate_handle))
//
// when it does (TAG_AFFILIATE = the field element of the bytes
// "earth.affiliate"), so whoever relays it cannot swap the handle.
//
// A new registration (or one re-entering after its last lapsed) appends the
// leaf, mints 1 ANML to pc_anml and the registrant's half of the reward to
// pc_erth, and, when it names affiliate_handle (a live handle: MsgBindHandle),
// mints the referrer's half itself, to the address the handle resolves to at
// execution: pc = PC(handle owner_pk, rho, rcm) with
//
//	rho = H(TAG_REFERRAL, nullifier, leaf_index, 0)
//	rcm = H(TAG_REFERRAL, nullifier, leaf_index, 1)
//
// (zk/privacy.ReferralOpening; TAG_REFERRAL = "earth.referral", nullifier the
// passport nullifier, leaf_index the new leaf's). The note has no ciphertext:
// its shielded_mint event carries owner_pk, rho and rcm, and the handle
// owner's wallet finds it by owner_pk. The registrant cannot redirect it. A
// live registration is a switch: the old leaf is zeroed and the new one
// appended, and nothing is paid (affiliate is then not checked). A switch to
// the idc the live registration already holds is refused (a replay).
//
// sighash fields: idc, pc_anml, Bytes(ciphertext_anml), pc_erth,
// Bytes(ciphertext_erth), affiliate (as in the binding),
// Bytes(signature_algorithm), then every public signal in order. The passport
// proof binds the identity, pcs and ciphertexts through its address input;
// the sighash binds the rest to the fee bundle.
type MsgRegister struct {
	Fee types.Bundle `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee"`
	// proof is the Barretenberg UltraHonk proof bytes (bb v5.0.0).
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// public_signals are the circuit public inputs as decimal strings.
	PublicSignals []string `protobuf:"bytes,3,rep,name=public_signals,json=publicSignals,proto3" json:"public_signals,omitempty"`
	// signature_algorithm selects the verifying key (e.g. "lean_poa_rsa2048_sha256").
	SignatureAlgorithm string `protobuf:"bytes,4,opt,name=signature_algorithm,json=signatureAlgorithm,proto3" json:"signature_algorithm,omitempty"`
	// dsc_der is the DER-encoded Document Signer certificate.
	DscDer []byte `protobuf:"bytes,5,opt,name=dsc_der,json=dscDer,proto3" json:"dsc_der,omitempty"`
	// idc is the identity commitment H(TAG_ID, id_secret), 32 bytes.
	Idc []byte `protobuf:"bytes,6,opt,name=idc,proto3" json:"idc,omitempty"`
	// pc_anml receives the registration's ANML note.
	PcAnml []byte `protobuf:"bytes,7,opt,name=pc_anml,json=pcAnml,proto3" json:"pc_anml,omitempty"`
	// ciphertext_anml / ciphertext_erth: each note's amount-blind v2
	// ciphertext (zk/privacy.EncryptBlindNote), exactly 177 bytes, required.
	CiphertextAnml []byte `protobuf:"bytes,8,opt,name=ciphertext_anml,json=ciphertextAnml,proto3" json:"ciphertext_anml,omitempty"`
	// pc_erth receives the registrant's half of the registration reward.
	PcErth         []byte `protobuf:"bytes,9,opt,name=pc_erth,json=pcErth,proto3" json:"pc_erth,omitempty"`
	CiphertextErth []byte `protobuf:"bytes,10,opt,name=ciphertext_erth,json=ciphertextErth,proto3" json:"ciphertext_erth,omitempty"`
	// affiliate_handle names the referrer (a live handle), empty for none.
	AffiliateHandle string `protobuf:"bytes,15,opt,name=affiliate_handle,json=affiliateHandle,proto3" json:"affiliate_handle,omitempty"`
}

func (m *MsgRegister) Reset()         { *m = MsgRegister{} }
func (m *MsgRegister) String() string { return proto.CompactTextString(m) }
func (*MsgRegister) ProtoMessage()    {}
func (*MsgRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_83fe5bb40ec19165, []int{2}
}
func (m *MsgRegister) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegister.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegister.Merge(m, src)
}
func (m *MsgRegister) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegister.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegister proto.InternalMessageInfo

func (m *MsgRegister) GetFee() types.Bundle {
	if m != nil {
		return m.Fee
	}
	return types.Bundle{}
}

func (m *MsgRegister) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *MsgRegister) GetPublicSignals() []string {
	if m != nil {
		return m.PublicSignals
	}
	return nil
}

func (m *MsgRegister) GetSignatureAlgorithm() string {
	if m != nil {
		return m.SignatureAlgorithm
	}
	return ""
}

func (m *MsgRegister) GetDscDer() []byte {
	if m != nil {
		return m.DscDer
	}
	return nil
}

func (m *MsgRegister) GetIdc() []byte {
	if m != nil {
		return m.Idc
	}
	return nil
}

func (m *MsgRegister) GetPcAnml() []byte {
	if m != nil {
		return m.PcAnml
	}
	return nil
}

func (m *MsgRegister) GetCiphertextAnml() []byte {
	if m != nil {
		return m.CiphertextAnml
	}
	return nil
}

func (m *MsgRegister) GetPcErth() []byte {
	if m != nil {
		return m.PcErth
	}
	return nil
}

func (m *MsgRegister) GetCiphertextErth() []byte {
	if m != nil {
		return m.CiphertextErth
	}
	return nil
}

func (m *MsgRegister) GetAffiliateHandle() string {
	if m != nil {
		return m.AffiliateHandle
	}
	return ""
}

// MsgRegisterResponse returns what the registration did.
type MsgRegisterResponse struct {
	// reward is the ERTH minted to pc_erth; zero on a switch.
	Reward cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=reward,proto3,customtype=cosmossdk.io/math.Int" json:"reward"`
	// switched is true when this moved a live registration to a new identity.
	Switched bool `protobuf:"varint,2,opt,name=switched,proto3" json:"switched,omitempty"`
	// leaf_index is the new identity leaf's position.
	LeafIndex uint64 `protobuf:"varint,3,opt,name=leaf_index,json=leafIndex,proto3" json:"leaf_index,omitempty"`
}

func (m *MsgRegisterResponse) Reset()         { *m = MsgRegisterResponse{} }
func (m *MsgRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterResponse) ProtoMessage()    {}
func (*MsgRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83fe5bb40ec19165, []int{3}
}
func (m *MsgRegisterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterResponse.Merge(m, src)
}
func (m *MsgRegisterResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterResponse proto.InternalMessageInfo

func (m *MsgRegisterResponse) GetSwitched() bool {
	if m != nil {
		return m.Switched
	}
	return false
}

func (m *MsgRegisterResponse) GetLeafIndex() uint64 {
	if m != nil {
		return m.LeafIndex
	}
	return 0
}

// MsgClaimAnml mints 1 ANML to pc, once per person per UTC day.
//
// membership is proven with scope zk/privacy.ClaimScope(day), excluded_dsc and
// excluded_country 0
// and max_activation the start of the previous UTC day. day must be today.
//
// sighash fields: day, pc, Bytes(ciphertext).
type MsgClaimAnml struct {
	Fee        types.Bundle `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee"`
	Membership Membership   `protobuf:"bytes,2,opt,name=membership,proto3" json:"membership"`
	Day        uint64       `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Pc         []byte       `protobuf:"bytes,4,opt,name=pc,proto3" json:"pc,omitempty"`
	// ciphertext is the ANML note's amount-blind v2 ciphertext, 177 bytes.
	Ciphertext []byte `protobuf:"bytes,5,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (m *MsgClaimAnml) Reset()         { *m = MsgClaimAnml{} }
func (m *MsgClaimAnml) String() string { return proto.CompactTextString(m) }
func (*MsgClaimAnml) ProtoMessage()    {}
func (*MsgClaimAnml) Descriptor() ([]byte, []int) {
	return fileDescriptor_83fe5bb40ec19165, []int{4}
}
func (m *MsgClaimAnml) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimAnml) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimAnml.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimAnml) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimAnml.Merge(m, src)
}
func (m *MsgClaimAnml) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimAnml) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimAnml.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimAnml proto.InternalMessageInfo

func (m *MsgClaimAnml) GetFee() types.Bundle {
	if m != nil {
		return m.Fee
	}
	return types.Bundle{}
}

func (m *MsgClaimAnml) GetMembership() Membership {
	if m != nil {
		return m.Membership
	}
	return Membership{}
}

func (m *MsgClaimAnml) GetDay() uint64 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *MsgClaimAnml) GetPc() []byte {
	if m != nil {
		return m.Pc
	}
	return nil
}

func (m *MsgClaimAnml) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

// MsgClaimAnmlResponse returns the ANML note's position.
type MsgClaimAnmlResponse struct {
	Position uint64 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (m *MsgClaimAnmlResponse) Reset()         { *m = MsgClaimAnmlResponse{} }
func (m *MsgClaimAnmlResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimAnmlResponse) ProtoMessage()    {}
func (*MsgClaimAnmlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83fe5bb40ec19165, []int{5}
}
func (m *MsgClaimAnmlResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimAnmlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimAnmlResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimAnmlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimAnmlResponse.Merge(m, src)
}
func (m *MsgClaimAnmlResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimAnmlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimAnmlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimAnmlResponse proto.InternalMessageInfo

func (m *MsgClaimAnmlResponse) GetPosition() uint64 {
	if m != nil {
		return m.Position
	}
	return 0
}

// MsgSetCaretaker casts, replaces or clears (empty percentages) the prover's
// caretaker split. The split is public; who cast it is not.
//
// membership is proven with scope zk/privacy.CaretakerScope(), excluded_dsc and
// excluded_country 0, max_activation NoBound (2^63 - 1: any) and
// max_predecessor this msg's max_predecessor, which must be strictly below
// now - caretaker_vote_seconds (or a held, longer one after governance
// lowered it) - 86400 (one day, the largest identity root window). A fresh
// registrant (predecessor_at 0) casts at once; an identity that replaced
// another waits until every split its predecessor could have cast has
// lapsed. The bound applies only to a prover holding no split: refreshing
// or changing one it holds takes any max_predecessor. The wallet names the
// bound (rounded down, say to the hour, so it
// says nothing about when the tx was made) because the chain's own changes
// every block and a proof must be made before its block is known. The split
// counts until now + caretaker_vote_seconds; the wallet refreshes it before
// then.
//
// sighash fields: for each entry, option_id then percent.
type MsgSetCaretaker struct {
	Fee         types.Bundle              `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee"`
	Membership  Membership                `protobuf:"bytes,2,opt,name=membership,proto3" json:"membership"`
	Percentages []types1.AllocationWeight `protobuf:"bytes,3,rep,name=percentages,proto3" json:"percentages"`
	// max_predecessor is the membership proof's max_predecessor (unix seconds).
	MaxPredecessor uint64 `protobuf:"varint,5,opt,name=max_predecessor,json=maxPredecessor,proto3" json:"max_predecessor,omitempty"`
}

func (m *MsgSetCaretaker) Reset()         { *m = MsgSetCaretaker{} }
func (m *MsgSetCaretaker) String() string { return proto.CompactTextString(m) }
func (*MsgSetCaretaker) ProtoMessage()    {}
func (*MsgSetCaretaker) Descriptor() ([]byte, []int) {
	return fileDescriptor_83fe5bb40ec19165, []int{6}
}
func (m *MsgSetCaretaker) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetCaretaker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetCaretaker.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetCaretaker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetCaretaker.Merge(m, src)
}
func (m *MsgSetCaretaker) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetCaretaker) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetCaretaker.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetCaretaker proto.InternalMessageInfo

func (m *MsgSetCaretaker) GetFee() types.Bundle {
	if m != nil {
		return m.Fee
	}
	return types.Bundle{}
}

func (m *MsgSetCaretaker) GetMembership() Membership {
	if m != nil {
		return m.Membership
	}
	return Membership{}
}

func (m *MsgSetCaretaker) GetPercentages() []types1.AllocationWeight {
	if m != nil {
		return m.Percentages
	}
	return nil
}

func (m *MsgSetCaretaker) GetMaxPredecessor() uint64 {
	if m != nil {
		return m.MaxPredecessor
	}
	return 0
}

// MsgSetCaretakerResponse reports when the split lapses (unix seconds), 0 when
// it was cleared.
type MsgSetCaretakerResponse struct {
	ExpiresAt int64 `protobuf:"varint,1,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (m *MsgSetCaretakerResponse) Reset()         { *m = MsgSetCaretakerResponse{} }
func (m *MsgSetCaretakerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetCaretakerResponse) ProtoMessage()    {}
func (*MsgSetCaretakerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83fe5bb40ec19165, []int{7}
}
func (m *MsgSetCaretakerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetCaretakerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetCaretakerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetCaretakerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetCaretakerResponse.Merge(m, src)
}
func (m *MsgSetCaretakerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetCaretakerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetCaretakerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetCaretakerResponse proto.InternalMessageInfo

func (m *MsgSetCaretakerResponse) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

// MsgBindHandle claims, renews, changes or releases the prover's handle
// (types.Handle): a name in the public directory for a shielded address.
//
// A handle is lowercase [a-z0-9-], 3 to 32 characters, no leading or
// trailing dash. One per human: membership is proven with scope zk/privacy.HandleScope()
// (Scope("handle")), excluded_dsc and excluded_country 0, max_activation
// NoBound (2^63 - 1) and max_predecessor this msg's max_predecessor.
//
//   - handle and address set, the prover holding a handle: renew it (the
//     same handle: lease now + handle_lease_seconds, address updated) or
//     change to another (the old one is released at once, the new one
//     claimed in the same msg). Any max_predecessor while the held handle is
//     live; in its renewal period, under the claim bound, as a claim.
//   - handle and address set, the prover holding none: claim a free handle.
//     max_predecessor must be strictly below now - the longest
//     handle_lease_seconds ever set - 86400: an identity that replaced
//     another waits until any handle its predecessor held has lapsed. A
//     fresh registrant claims at once.
//   - both empty: release the prover's handle at once.
//
// A handle held by another nullifier (live, or in its renewal period) is
// refused.
//
// address is the shielded address (zk/privacy: bech32m "erthz1...", owner_pk
// and ek_pub), canonical lowercase. No consent is needed: naming someone
// else's shielded address only sends the binder's referrals to them.
//
// sighash fields: Bytes(handle), owner_pk, Bytes(ek_pub) (Bytes of nothing,
// 0 and Bytes of nothing for a release).
type MsgBindHandle struct {
	Fee        types.Bundle `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee"`
	Membership Membership   `protobuf:"bytes,2,opt,name=membership,proto3" json:"membership"`
	Handle     string       `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	// address is the shielded address the handle resolves to.
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// max_predecessor is the membership proof's max_predecessor (unix seconds).
	MaxPredecessor uint64 `protobuf:"varint,6,opt,name=max_predecessor,json=maxPredecessor,proto3" json:"max_predecessor,omitempty"`
}

func (m *MsgBindHandle) Reset()         { *m = MsgBindHandle{} }
func (m *MsgBindHandle) String() string { return proto.CompactTextString(m) }
func (*MsgBindHandle) ProtoMessage()    {}
func (*MsgBindHandle) Descriptor() ([]byte, []int) {
	return fileDescriptor_83fe5bb40ec19165, []int{8}
}
func (m *MsgBindHandle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBindHandle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBindHandle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBindHandle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBindHandle.Merge(m, src)
}
func (m *MsgBindHandle) XXX_Size() int {
	return m.Size()
}
func (m *MsgBindHandle) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBindHandle.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBindHandle proto.InternalMessageInfo

func (m *MsgBindHandle) GetFee() types.Bundle {
	if m != nil {
		return m.Fee
	}
	return types.Bundle{}
}

func (m *MsgBindHandle) GetMembership() Membership {
	if m != nil {
		return m.Membership
	}
	return Membership{}
}

func (m *MsgBindHandle) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

func (m *MsgBindHandle) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgBindHandle) GetMaxPredecessor() uint64 {
	if m != nil {
		return m.MaxPredecessor
	}
	return 0
}

// MsgBindHandleResponse reports when the lease lapses (unix seconds), 0 when
// the handle was released.
type MsgBindHandleResponse struct {
	ExpiresAt int64 `protobuf:"varint,1,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (m *MsgBindHandleResponse) Reset()         { *m = MsgBindHandleResponse{} }
func (m *MsgBindHandleResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBindHandleResponse) ProtoMessage()    {}
func (*MsgBindHandleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83fe5bb40ec19165, []int{9}
}
func (m *MsgBindHandleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBindHandleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBindHandleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBindHandleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBindHandleResponse.Merge(m, src)
}
func (m *MsgBindHandleResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBindHandleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBindHandleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBindHandleResponse proto.InternalMessageInfo

func (m *MsgBindHandleResponse) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "earth.personhood.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "earth.personhood.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgRegister)(nil), "earth.personhood.v1.MsgRegister")
	proto.RegisterType((*MsgRegisterResponse)(nil), "earth.personhood.v1.MsgRegisterResponse")
	proto.RegisterType((*MsgClaimAnml)(nil), "earth.personhood.v1.MsgClaimAnml")
	proto.RegisterType((*MsgClaimAnmlResponse)(nil), "earth.personhood.v1.MsgClaimAnmlResponse")
	proto.RegisterType((*MsgSetCaretaker)(nil), "earth.personhood.v1.MsgSetCaretaker")
	proto.RegisterType((*MsgSetCaretakerResponse)(nil), "earth.personhood.v1.MsgSetCaretakerResponse")
	proto.RegisterType((*MsgBindHandle)(nil), "earth.personhood.v1.MsgBindHandle")
	proto.RegisterType((*MsgBindHandleResponse)(nil), "earth.personhood.v1.MsgBindHandleResponse")
}

func init() { proto.RegisterFile("earth/personhood/v1/tx.proto", fileDescriptor_83fe5bb40ec19165) }

var fileDescriptor_83fe5bb40ec19165 = []byte{
	// 1074 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0xae, 0x1b, 0x37, 0x4d, 0x5e, 0xd2, 0x34, 0xb8, 0x5d, 0xea, 0x06, 0x36, 0x0d, 0xd6, 0x2e,
	0x74, 0x0b, 0x4d, 0x94, 0x22, 0x56, 0x88, 0x03, 0x52, 0x53, 0x56, 0xa2, 0x45, 0x91, 0x56, 0xae,
	0x00, 0x81, 0x90, 0xa2, 0x89, 0x3d, 0xb5, 0x47, 0xb5, 0x3d, 0xd6, 0xcc, 0x34, 0x4d, 0x6f, 0x88,
	0x23, 0x27, 0x2e, 0x1c, 0xf8, 0x07, 0x1c, 0x7b, 0xd8, 0x1f, 0xc0, 0x71, 0xc5, 0x69, 0xb5, 0x27,
	0xc4, 0x61, 0x41, 0xad, 0x50, 0xff, 0x03, 0x27, 0xe4, 0xb1, 0x63, 0xbb, 0x25, 0x51, 0x57, 0x2b,
	0x24, 0x2e, 0xd6, 0xbc, 0xf7, 0xbe, 0xf7, 0xe6, 0xbd, 0x6f, 0xde, 0x9b, 0x31, 0xbc, 0x89, 0x11,
	0x13, 0x6e, 0x27, 0xc4, 0x8c, 0xd3, 0xc0, 0xa5, 0xd4, 0xee, 0x8c, 0xba, 0x1d, 0x31, 0x6e, 0x87,
	0x8c, 0x0a, 0xaa, 0xad, 0x48, 0x6b, 0x3b, 0xb3, 0xb6, 0x47, 0xdd, 0xc6, 0x6b, 0xc8, 0x27, 0x01,
	0xed, 0xc8, 0x6f, 0x8c, 0x6b, 0xac, 0x59, 0x94, 0xfb, 0x94, 0x77, 0x7c, 0xee, 0x44, 0xfe, 0x3e,
	0x77, 0x12, 0xc3, 0x7a, 0x6c, 0x18, 0x48, 0xa9, 0x13, 0x0b, 0x89, 0xe9, 0x5e, 0xbc, 0x33, 0xf2,
	0x3c, 0x6a, 0x21, 0x41, 0x68, 0x10, 0x79, 0x66, 0x52, 0x82, 0x6a, 0x4d, 0xcb, 0x2f, 0x44, 0x0c,
	0xf9, 0x93, 0x38, 0x6f, 0x4f, 0x43, 0x30, 0xec, 0x10, 0x2e, 0xd8, 0x94, 0x48, 0xdc, 0x25, 0xd8,
	0xb3, 0xb1, 0x44, 0x4d, 0xd6, 0x09, 0x62, 0xd5, 0xa1, 0x0e, 0x8d, 0x33, 0x8d, 0x56, 0xb1, 0xd6,
	0xf8, 0x45, 0x81, 0xe5, 0x3e, 0x77, 0x3e, 0x0f, 0x6d, 0x24, 0xf0, 0x63, 0xb9, 0xb3, 0xf6, 0x10,
	0xca, 0xe8, 0x44, 0xb8, 0x94, 0x11, 0x71, 0xa6, 0x2b, 0x2d, 0x65, 0xb3, 0xdc, 0xd3, 0x9f, 0x3f,
	0xd9, 0x5e, 0x4d, 0x0a, 0xdc, 0xb5, 0x6d, 0x86, 0x39, 0x3f, 0x14, 0x8c, 0x04, 0x8e, 0x99, 0x41,
	0xb5, 0x8f, 0xa1, 0x18, 0xe7, 0xae, 0xcf, 0xb7, 0x94, 0xcd, 0xca, 0xce, 0x1b, 0xed, 0x29, 0x04,
	0xb7, 0xe3, 0x4d, 0x7a, 0xe5, 0xa7, 0x2f, 0x36, 0xe6, 0x7e, 0xbe, 0x3a, 0xdf, 0x52, 0xcc, 0xc4,
	0xeb, 0xa3, 0x0f, 0xbe, 0xbb, 0x3a, 0xdf, 0xca, 0xe2, 0x7d, 0x7f, 0x75, 0xbe, 0x65, 0xc4, 0x65,
	0x8d, 0xf3, 0x04, 0xdc, 0x48, 0xd7, 0x58, 0x87, 0xb5, 0x1b, 0x2a, 0x13, 0xf3, 0x90, 0x06, 0x1c,
	0x1b, 0x7f, 0x14, 0xa0, 0xd2, 0xe7, 0x8e, 0x29, 0xf9, 0xc2, 0x4c, 0xeb, 0x42, 0xe1, 0x08, 0x63,
	0x59, 0x53, 0x65, 0x67, 0x3d, 0x49, 0x2f, 0xe5, 0x69, 0xd4, 0x6d, 0xf7, 0x4e, 0x02, 0xdb, 0xc3,
	0x3d, 0x35, 0x4a, 0xce, 0x8c, 0xb0, 0xda, 0x2a, 0x2c, 0x84, 0x8c, 0xd2, 0x23, 0x59, 0x53, 0xd5,
	0x8c, 0x05, 0xed, 0x3e, 0xd4, 0xc2, 0x93, 0xa1, 0x47, 0xac, 0x01, 0x27, 0x4e, 0x80, 0x3c, 0xae,
	0x17, 0x5a, 0x85, 0xcd, 0xb2, 0xb9, 0x14, 0x6b, 0x0f, 0x63, 0xa5, 0xd6, 0x81, 0x15, 0x69, 0x17,
	0x27, 0x0c, 0x0f, 0x90, 0xe7, 0x44, 0x75, 0xb9, 0xbe, 0xae, 0x46, 0x9c, 0x9a, 0x5a, 0x6a, 0xda,
	0x9d, 0x58, 0xb4, 0x35, 0x58, 0xb4, 0xb9, 0x35, 0xb0, 0x31, 0xd3, 0x17, 0xe4, 0x7e, 0x45, 0x9b,
	0x5b, 0x9f, 0x60, 0xa6, 0xd5, 0xa1, 0x40, 0x6c, 0x4b, 0x2f, 0x4a, 0x65, 0xb4, 0x8c, 0xa0, 0xa1,
	0x35, 0x40, 0x81, 0xef, 0xe9, 0x8b, 0x31, 0x34, 0xb4, 0x76, 0x03, 0xdf, 0xd3, 0xde, 0x81, 0x65,
	0x8b, 0x84, 0x2e, 0x66, 0x02, 0x8f, 0x45, 0x0c, 0x28, 0x49, 0x40, 0x2d, 0x53, 0x4b, 0x60, 0x1c,
	0x01, 0x33, 0xe1, 0xea, 0xe5, 0x49, 0x84, 0x47, 0x4c, 0xb8, 0x37, 0x22, 0x48, 0x00, 0xdc, 0x8c,
	0x20, 0x81, 0x0f, 0xa0, 0x8e, 0x8e, 0x8e, 0x88, 0x47, 0x90, 0xc0, 0x03, 0x17, 0x45, 0xdc, 0xe9,
	0xcb, 0xb2, 0xb8, 0xe5, 0x54, 0xff, 0xa9, 0x54, 0x1f, 0xa8, 0xa5, 0x4a, 0xbd, 0x7a, 0xa0, 0x96,
	0xaa, 0xf5, 0xa5, 0x03, 0xb5, 0xb4, 0x54, 0xaf, 0x1d, 0xa8, 0xa5, 0x5a, 0x7d, 0xd9, 0xac, 0x66,
	0x01, 0x42, 0xcb, 0x5c, 0xcd, 0xa4, 0x6c, 0x2b, 0xb3, 0x9c, 0x6a, 0xcd, 0x5a, 0x0e, 0x40, 0x6d,
	0x6c, 0xfc, 0xa8, 0xc0, 0x4a, 0xee, 0x84, 0x27, 0x27, 0xaf, 0xed, 0x41, 0x91, 0xe1, 0x53, 0xc4,
	0xec, 0xa4, 0x81, 0xdf, 0x8d, 0x4e, 0xf4, 0xf7, 0x17, 0x1b, 0x77, 0xe2, 0x26, 0xe6, 0xf6, 0x71,
	0x9b, 0xd0, 0x8e, 0x8f, 0x84, 0xdb, 0xde, 0x0f, 0xc4, 0xf3, 0x27, 0xdb, 0x90, 0x74, 0xf7, 0x7e,
	0x20, 0xcc, 0xc4, 0x55, 0x6b, 0x40, 0x89, 0x9f, 0x12, 0x61, 0xb9, 0xd8, 0x96, 0xc7, 0x5f, 0x32,
	0x53, 0x59, 0xbb, 0x0b, 0xe0, 0x61, 0x74, 0x34, 0x20, 0x81, 0x8d, 0xc7, 0x7a, 0xa1, 0xa5, 0x6c,
	0xaa, 0x66, 0x39, 0xd2, 0xec, 0x47, 0x0a, 0xe3, 0x57, 0x05, 0xaa, 0x7d, 0xee, 0xec, 0x79, 0x88,
	0xf8, 0x92, 0xec, 0x57, 0x68, 0xbd, 0x47, 0x00, 0x3e, 0xf6, 0x87, 0x98, 0x71, 0x97, 0x84, 0xc9,
	0x4c, 0x6d, 0x4c, 0x9d, 0xa9, 0x7e, 0x0a, 0x4b, 0xfc, 0x73, 0x8e, 0x51, 0xeb, 0xd8, 0xe8, 0x2c,
	0x49, 0x31, 0x5a, 0x6a, 0x35, 0x98, 0x0f, 0x2d, 0xd9, 0x85, 0x55, 0x73, 0x3e, 0xb4, 0xb4, 0x26,
	0x40, 0xc6, 0x76, 0xd2, 0x78, 0x39, 0x8d, 0xb1, 0x03, 0xab, 0xf9, 0x5a, 0x52, 0x92, 0x1b, 0x50,
	0x0a, 0x29, 0x27, 0xd1, 0x35, 0x24, 0x0b, 0x53, 0xcd, 0x54, 0x36, 0x7e, 0x9a, 0x97, 0x17, 0xcb,
	0x21, 0x16, 0x7b, 0x88, 0x61, 0x81, 0x8e, 0x5f, 0x6d, 0xfc, 0xfe, 0x23, 0x0e, 0xfa, 0x50, 0x09,
	0x31, 0xb3, 0x70, 0x20, 0x90, 0x83, 0xe3, 0x61, 0xad, 0xec, 0xdc, 0x4f, 0xe2, 0xe4, 0xae, 0xe5,
	0x51, 0xb7, 0xbd, 0x9b, 0x4a, 0x5f, 0x62, 0xe2, 0xb8, 0x22, 0x89, 0x96, 0xf7, 0x8f, 0x06, 0xc4,
	0x47, 0xe3, 0x41, 0xc8, 0xb0, 0x8d, 0x2d, 0xcc, 0x39, 0x8d, 0xc7, 0x55, 0x35, 0x6b, 0x3e, 0x1a,
	0x3f, 0xce, 0xb4, 0x07, 0x6a, 0x49, 0xad, 0x2f, 0x48, 0xed, 0x00, 0x59, 0x82, 0x8c, 0x64, 0x5c,
	0xe3, 0x43, 0x79, 0x63, 0xe5, 0xa9, 0x49, 0x29, 0xbd, 0x0b, 0x80, 0xc7, 0x21, 0x61, 0x98, 0x0f,
	0x90, 0x90, 0x4c, 0x15, 0xcc, 0x72, 0xa2, 0xd9, 0x15, 0xc6, 0xdf, 0x0a, 0x2c, 0xf5, 0xb9, 0xd3,
	0x23, 0x81, 0x1d, 0xcf, 0xd5, 0xff, 0xc8, 0xe9, 0xeb, 0x50, 0x4c, 0x46, 0xbe, 0x20, 0x47, 0x3e,
	0x91, 0x34, 0x1d, 0x16, 0x51, 0xfc, 0x44, 0x24, 0x17, 0xdd, 0x44, 0x9c, 0x46, 0x5b, 0x71, 0x06,
	0x6d, 0x0b, 0xf5, 0xe2, 0xbf, 0x68, 0x7b, 0x08, 0x77, 0xae, 0xd5, 0xfe, 0x92, 0xa4, 0xed, 0xfc,
	0x55, 0x80, 0x42, 0x9f, 0x3b, 0xda, 0x10, 0xaa, 0xd7, 0xde, 0xb9, 0x7b, 0xd3, 0x6b, 0xbe, 0xfe,
	0x96, 0x34, 0xde, 0x7b, 0x19, 0x54, 0x9a, 0xca, 0x17, 0x50, 0x4a, 0x5f, 0x9b, 0xd6, 0x2c, 0xcf,
	0x09, 0xa2, 0xb1, 0x79, 0x1b, 0x22, 0x8d, 0xfb, 0x15, 0x94, 0xb3, 0xbb, 0xe4, 0xad, 0x59, 0x6e,
	0x29, 0xa4, 0xf1, 0xe0, 0x56, 0x48, 0x1a, 0x7a, 0x08, 0xd5, 0x6b, 0x53, 0x3a, 0x93, 0x96, 0x3c,
	0x6a, 0x36, 0x2d, 0x53, 0xdb, 0xfa, 0x1b, 0x80, 0x5c, 0xcf, 0x1a, 0xb3, 0x7c, 0x33, 0x4c, 0x63,
	0xeb, 0x76, 0xcc, 0x24, 0x7a, 0x63, 0xe1, 0xdb, 0xe8, 0x3f, 0xa2, 0xf7, 0xd9, 0xd3, 0x8b, 0xa6,
	0xf2, 0xec, 0xa2, 0xa9, 0xfc, 0x79, 0xd1, 0x54, 0x7e, 0xb8, 0x6c, 0xce, 0x3d, 0xbb, 0x6c, 0xce,
	0xfd, 0x76, 0xd9, 0x9c, 0xfb, 0xba, 0xeb, 0x10, 0xe1, 0x9e, 0x0c, 0xdb, 0x16, 0xf5, 0x3b, 0x32,
	0xec, 0x76, 0x80, 0xc5, 0x29, 0x65, 0xc7, 0x9d, 0x29, 0xff, 0x17, 0xe2, 0x2c, 0xc4, 0x7c, 0x58,
	0x94, 0xff, 0x47, 0xef, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x17, 0x23, 0x1e, 0x1c, 0x43, 0x0a,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// Register registers a passport and writes its holder's identity leaf.
	Register(ctx context.Context, in *MsgRegister, opts ...grpc.CallOption) (*MsgRegisterResponse, error)
	// ClaimAnml mints a registered human's daily ANML to a note.
	ClaimAnml(ctx context.Context, in *MsgClaimAnml, opts ...grpc.CallOption) (*MsgClaimAnmlResponse, error)
	// SetCaretaker casts or refreshes a registered human's caretaker split.
	SetCaretaker(ctx context.Context, in *MsgSetCaretaker, opts ...grpc.CallOption) (*MsgSetCaretakerResponse, error)
	// BindHandle claims, refreshes, changes or releases a registered human's
	// handle: a name in the public directory for a shielded address.
	BindHandle(ctx context.Context, in *MsgBindHandle, opts ...grpc.CallOption) (*MsgBindHandleResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/earth.personhood.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Register(ctx context.Context, in *MsgRegister, opts ...grpc.CallOption) (*MsgRegisterResponse, error) {
	out := new(MsgRegisterResponse)
	err := c.cc.Invoke(ctx, "/earth.personhood.v1.Msg/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimAnml(ctx context.Context, in *MsgClaimAnml, opts ...grpc.CallOption) (*MsgClaimAnmlResponse, error) {
	out := new(MsgClaimAnmlResponse)
	err := c.cc.Invoke(ctx, "/earth.personhood.v1.Msg/ClaimAnml", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetCaretaker(ctx context.Context, in *MsgSetCaretaker, opts ...grpc.CallOption) (*MsgSetCaretakerResponse, error) {
	out := new(MsgSetCaretakerResponse)
	err := c.cc.Invoke(ctx, "/earth.personhood.v1.Msg/SetCaretaker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BindHandle(ctx context.Context, in *MsgBindHandle, opts ...grpc.CallOption) (*MsgBindHandleResponse, error) {
	out := new(MsgBindHandleResponse)
	err := c.cc.Invoke(ctx, "/earth.personhood.v1.Msg/BindHandle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// Register registers a passport and writes its holder's identity leaf.
	Register(context.Context, *MsgRegister) (*MsgRegisterResponse, error)
	// ClaimAnml mints a registered human's daily ANML to a note.
	ClaimAnml(context.Context, *MsgClaimAnml) (*MsgClaimAnmlResponse, error)
	// SetCaretaker casts or refreshes a registered human's caretaker split.
	SetCaretaker(context.Context, *MsgSetCaretaker) (*MsgSetCaretakerResponse, error)
	// BindHandle claims, refreshes, changes or releases a registered human's
	// handle: a name in the public directory for a shielded address.
	BindHandle(context.Context, *MsgBindHandle) (*MsgBindHandleResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) Register(ctx context.Context, req *MsgRegister) (*MsgRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedMsgServer) ClaimAnml(ctx context.Context, req *MsgClaimAnml) (*MsgClaimAnmlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimAnml not implemented")
}
func (*UnimplementedMsgServer) SetCaretaker(ctx context.Context, req *MsgSetCaretaker) (*MsgSetCaretakerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCaretaker not implemented")
}
func (*UnimplementedMsgServer) BindHandle(ctx context.Context, req *MsgBindHandle) (*MsgBindHandleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindHandle not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.personhood.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.personhood.v1.Msg/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Register(ctx, req.(*MsgRegister))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimAnml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimAnml)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimAnml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.personhood.v1.Msg/ClaimAnml",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimAnml(ctx, req.(*MsgClaimAnml))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetCaretaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetCaretaker)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetCaretaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.personhood.v1.Msg/SetCaretaker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetCaretaker(ctx, req.(*MsgSetCaretaker))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BindHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBindHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BindHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/earth.personhood.v1.Msg/BindHandle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BindHandle(ctx, req.(*MsgBindHandle))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "earth.personhood.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Msg_Register_Handler,
		},
		{
			MethodName: "ClaimAnml",
			Handler:    _Msg_ClaimAnml_Handler,
		},
		{
			MethodName: "SetCaretaker",
			Handler:    _Msg_SetCaretaker_Handler,
		},
		{
			MethodName: "BindHandle",
			Handler:    _Msg_BindHandle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "earth/personhood/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRegister) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegister) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegister) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AffiliateHandle) > 0 {
		i -= len(m.AffiliateHandle)
		copy(dAtA[i:], m.AffiliateHandle)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AffiliateHandle)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.CiphertextErth) > 0 {
		i -= len(m.CiphertextErth)
		copy(dAtA[i:], m.CiphertextErth)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CiphertextErth)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.PcErth) > 0 {
		i -= len(m.PcErth)
		copy(dAtA[i:], m.PcErth)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PcErth)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.CiphertextAnml) > 0 {
		i -= len(m.CiphertextAnml)
		copy(dAtA[i:], m.CiphertextAnml)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CiphertextAnml)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.PcAnml) > 0 {
		i -= len(m.PcAnml)
		copy(dAtA[i:], m.PcAnml)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PcAnml)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Idc) > 0 {
		i -= len(m.Idc)
		copy(dAtA[i:], m.Idc)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Idc)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DscDer) > 0 {
		i -= len(m.DscDer)
		copy(dAtA[i:], m.DscDer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DscDer)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SignatureAlgorithm) > 0 {
		i -= len(m.SignatureAlgorithm)
		copy(dAtA[i:], m.SignatureAlgorithm)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignatureAlgorithm)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PublicSignals) > 0 {
		for iNdEx := len(m.PublicSignals) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PublicSignals[iNdEx])
			copy(dAtA[i:], m.PublicSignals[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.PublicSignals[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Fee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgRegisterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LeafIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LeafIndex))
		i--
		dAtA[i] = 0x18
	}
	if m.Switched {
		i--
		if m.Switched {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.Reward.Size()
		i -= size
		if _, err := m.Reward.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgClaimAnml) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimAnml) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimAnml) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ciphertext) > 0 {
		i -= len(m.Ciphertext)
		copy(dAtA[i:], m.Ciphertext)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Ciphertext)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Pc) > 0 {
		i -= len(m.Pc)
		copy(dAtA[i:], m.Pc)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Pc)))
		i--
		dAtA[i] = 0x22
	}
	if m.Day != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Day))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.Membership.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Fee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgClaimAnmlResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimAnmlResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimAnmlResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Position != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Position))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetCaretaker) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetCaretaker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetCaretaker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxPredecessor != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MaxPredecessor))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Percentages) > 0 {
		for iNdEx := len(m.Percentages) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Percentages[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.Membership.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Fee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgSetCaretakerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetCaretakerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetCaretakerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresAt != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgBindHandle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBindHandle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBindHandle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxPredecessor != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MaxPredecessor))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Handle) > 0 {
		i -= len(m.Handle)
		copy(dAtA[i:], m.Handle)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Handle)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Membership.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Fee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgBindHandleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBindHandleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBindHandleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresAt != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRegister) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Fee.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.PublicSignals) > 0 {
		for _, s := range m.PublicSignals {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.SignatureAlgorithm)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DscDer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Idc)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PcAnml)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CiphertextAnml)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PcErth)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CiphertextErth)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AffiliateHandle)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Reward.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.Switched {
		n += 2
	}
	if m.LeafIndex != 0 {
		n += 1 + sovTx(uint64(m.LeafIndex))
	}
	return n
}

func (m *MsgClaimAnml) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Fee.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.Membership.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.Day != 0 {
		n += 1 + sovTx(uint64(m.Day))
	}
	l = len(m.Pc)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Ciphertext)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimAnmlResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Position != 0 {
		n += 1 + sovTx(uint64(m.Position))
	}
	return n
}

func (m *MsgSetCaretaker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Fee.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.Membership.Size()
	n += 1 + l + sovTx(uint64(l))
	if len(m.Percentages) > 0 {
		for _, e := range m.Percentages {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.MaxPredecessor != 0 {
		n += 1 + sovTx(uint64(m.MaxPredecessor))
	}
	return n
}

func (m *MsgSetCaretakerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ExpiresAt != 0 {
		n += 1 + sovTx(uint64(m.ExpiresAt))
	}
	return n
}

func (m *MsgBindHandle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Fee.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.Membership.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Handle)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MaxPredecessor != 0 {
		n += 1 + sovTx(uint64(m.MaxPredecessor))
	}
	return n
}

func (m *MsgBindHandleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ExpiresAt != 0 {
		n += 1 + sovTx(uint64(m.ExpiresAt))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegister) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegister: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegister: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicSignals", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicSignals = append(m.PublicSignals, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignatureAlgorithm", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignatureAlgorithm = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DscDer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DscDer = append(m.DscDer[:0], dAtA[iNdEx:postIndex]...)
			if m.DscDer == nil {
				m.DscDer = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Idc", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Idc = append(m.Idc[:0], dAtA[iNdEx:postIndex]...)
			if m.Idc == nil {
				m.Idc = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PcAnml", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PcAnml = append(m.PcAnml[:0], dAtA[iNdEx:postIndex]...)
			if m.PcAnml == nil {
				m.PcAnml = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CiphertextAnml", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CiphertextAnml = append(m.CiphertextAnml[:0], dAtA[iNdEx:postIndex]...)
			if m.CiphertextAnml == nil {
				m.CiphertextAnml = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PcErth", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PcErth = append(m.PcErth[:0], dAtA[iNdEx:postIndex]...)
			if m.PcErth == nil {
				m.PcErth = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CiphertextErth", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CiphertextErth = append(m.CiphertextErth[:0], dAtA[iNdEx:postIndex]...)
			if m.CiphertextErth == nil {
				m.CiphertextErth = []byte{}
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AffiliateHandle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AffiliateHandle = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Switched", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Switched = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeafIndex", wireType)
			}
			m.LeafIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeafIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimAnml) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimAnml: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimAnml: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Membership", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Membership.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Day", wireType)
			}
			m.Day = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Day |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pc", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pc = append(m.Pc[:0], dAtA[iNdEx:postIndex]...)
			if m.Pc == nil {
				m.Pc = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ciphertext", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ciphertext = append(m.Ciphertext[:0], dAtA[iNdEx:postIndex]...)
			if m.Ciphertext == nil {
				m.Ciphertext = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimAnmlResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimAnmlResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimAnmlResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			m.Position = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Position |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetCaretaker) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetCaretaker: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetCaretaker: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Membership", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Membership.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Percentages", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Percentages = append(m.Percentages, types1.AllocationWeight{})
			if err := m.Percentages[len(m.Percentages)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPredecessor", wireType)
			}
			m.MaxPredecessor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPredecessor |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetCaretakerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetCaretakerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetCaretakerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBindHandle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBindHandle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBindHandle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Membership", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Membership.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Handle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Handle = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPredecessor", wireType)
			}
			m.MaxPredecessor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPredecessor |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBindHandleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBindHandleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBindHandleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
