package types

// Events.
const (
	EventTypeDelegate       = "shieldedstaking_delegate"
	EventTypeUndelegate     = "shieldedstaking_undelegate"
	EventTypeClaim          = "shieldedstaking_claim"
	EventTypeEpoch          = "shieldedstaking_epoch"
	EventTypeEpochValidator = "shieldedstaking_epoch_validator"
	EventTypeEpochFailure   = "shieldedstaking_epoch_failure"
	EventTypeMatured        = "shieldedstaking_matured"
	EventTypeSlashHaircut   = "shieldedstaking_slash_haircut"
	EventTypeStakeVote      = "shieldedstaking_stake_vote"
	EventTypeSnapshot       = "shieldedstaking_snapshot"
	EventTypePosition       = "shieldedstaking_position"
	EventTypeInvariant      = "shieldedstaking_invariant_broken"
	EventTypeSelfBond       = "shieldedstaking_self_bond_compounded"

	AttributeKeyValidator   = "validator"
	AttributeKeyAmount      = "amount"
	AttributeKeyDerth       = "derth"
	AttributeKeyValue       = "value"
	AttributeKeyDenom       = "denom"
	AttributeKeyEpoch       = "epoch"
	AttributeKeyRate        = "rate"
	AttributeKeySupply      = "supply"
	AttributeKeyRewards     = "rewards"
	AttributeKeyDelegated   = "delegated"
	AttributeKeyUndelegated = "undelegated"
	AttributeKeyError       = "error"
	AttributeKeyStage       = "stage"
	AttributeKeyPayout      = "payout"
	AttributeKeyProposal    = "proposal_id"
	AttributeKeyWeight      = "weight"
	AttributeKeyOptions     = "options"
	AttributeKeyPosition    = "position_id"
	AttributeKeyAction      = "action"
	AttributeKeyRoot        = "root"
	AttributeKeyFraction    = "fraction"
)
