// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: earth/shieldedstaking/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines private staking's genesis state. The SDK delegations
// and unbonding entries it books against live in x/staking's genesis.
type GenesisState struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// epoch is absent at launch: the first epoch starts at InitGenesis.
	Epoch          *Epoch             `protobuf:"bytes,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Validators     []ValidatorState   `protobuf:"bytes,3,rep,name=validators,proto3" json:"validators"`
	UnbondRecords  []UnbondRecord     `protobuf:"bytes,4,rep,name=unbond_records,json=unbondRecords,proto3" json:"unbond_records"`
	Positions      []Position         `protobuf:"bytes,5,rep,name=positions,proto3" json:"positions"`
	NextPositionId uint64             `protobuf:"varint,6,opt,name=next_position_id,json=nextPositionId,proto3" json:"next_position_id,omitempty"`
	Snapshots      []ProposalSnapshot `protobuf:"bytes,7,rep,name=snapshots,proto3" json:"snapshots"`
	Votes          []StakeVote        `protobuf:"bytes,8,rep,name=votes,proto3" json:"votes"`
	// The stake note tree: every leaf in order, the spent nullifiers in the
	// order they were inserted into the stake nullifier tree (InitGenesis
	// re-inserts them in that order, rebuilding the same tree and root), and
	// the note roots still in the window (the latest last).
	StakeCommitments [][]byte    `protobuf:"bytes,9,rep,name=stake_commitments,json=stakeCommitments,proto3" json:"stake_commitments,omitempty"`
	StakeNullifiers  [][]byte    `protobuf:"bytes,10,rep,name=stake_nullifiers,json=stakeNullifiers,proto3" json:"stake_nullifiers,omitempty"`
	StakeRoots       []StakeRoot `protobuf:"bytes,11,rep,name=stake_roots,json=stakeRoots,proto3" json:"stake_roots"`
	// snapshot_seq is the last snapshot sequence number issued.
	SnapshotSeq       uint64             `protobuf:"varint,12,opt,name=snapshot_seq,json=snapshotSeq,proto3" json:"snapshot_seq,omitempty"`
	SupplyCheckpoints []SupplyCheckpoint `protobuf:"bytes,13,rep,name=supply_checkpoints,json=supplyCheckpoints,proto3" json:"supply_checkpoints"`
	EpochSweep        *EpochSweep        `protobuf:"bytes,14,opt,name=epoch_sweep,json=epochSweep,proto3" json:"epoch_sweep,omitempty"`
	// pending_releases are removed validators (operator address bytes) whose
	// reward escrow release failed; InitGenesis records their escrows again and
	// the epoch end retries the release. Without them an exported chain would
	// forget the escrow, and its balance with it.
	PendingReleases [][]byte `protobuf:"bytes,15,rep,name=pending_releases,json=pendingReleases,proto3" json:"pending_releases,omitempty"`
	// retiring_escrows are the scheduled retirements of operators that removed
	// their whole self-bond (escrow.go), kept at their original release time.
	RetiringEscrows []RetiringEscrow `protobuf:"bytes,16,rep,name=retiring_escrows,json=retiringEscrows,proto3" json:"retiring_escrows"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_144db389311a6ed1, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetEpoch() *Epoch {
	if m != nil {
		return m.Epoch
	}
	return nil
}

func (m *GenesisState) GetValidators() []ValidatorState {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *GenesisState) GetUnbondRecords() []UnbondRecord {
	if m != nil {
		return m.UnbondRecords
	}
	return nil
}

func (m *GenesisState) GetPositions() []Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *GenesisState) GetNextPositionId() uint64 {
	if m != nil {
		return m.NextPositionId
	}
	return 0
}

func (m *GenesisState) GetSnapshots() []ProposalSnapshot {
	if m != nil {
		return m.Snapshots
	}
	return nil
}

func (m *GenesisState) GetVotes() []StakeVote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *GenesisState) GetStakeCommitments() [][]byte {
	if m != nil {
		return m.StakeCommitments
	}
	return nil
}

func (m *GenesisState) GetStakeNullifiers() [][]byte {
	if m != nil {
		return m.StakeNullifiers
	}
	return nil
}

func (m *GenesisState) GetStakeRoots() []StakeRoot {
	if m != nil {
		return m.StakeRoots
	}
	return nil
}

func (m *GenesisState) GetSnapshotSeq() uint64 {
	if m != nil {
		return m.SnapshotSeq
	}
	return 0
}

func (m *GenesisState) GetSupplyCheckpoints() []SupplyCheckpoint {
	if m != nil {
		return m.SupplyCheckpoints
	}
	return nil
}

func (m *GenesisState) GetEpochSweep() *EpochSweep {
	if m != nil {
		return m.EpochSweep
	}
	return nil
}

func (m *GenesisState) GetPendingReleases() [][]byte {
	if m != nil {
		return m.PendingReleases
	}
	return nil
}

func (m *GenesisState) GetRetiringEscrows() []RetiringEscrow {
	if m != nil {
		return m.RetiringEscrows
	}
	return nil
}

// RetiringEscrow is a scheduled reward-escrow retirement: validator's escrow
// is paid out at release_at (unix nanoseconds) if its operator has not bonded
// again.
type RetiringEscrow struct {
	ReleaseAt int64  `protobuf:"varint,1,opt,name=release_at,json=releaseAt,proto3" json:"release_at,omitempty"`
	Validator []byte `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
}

func (m *RetiringEscrow) Reset()         { *m = RetiringEscrow{} }
func (m *RetiringEscrow) String() string { return proto.CompactTextString(m) }
func (*RetiringEscrow) ProtoMessage()    {}
func (*RetiringEscrow) Descriptor() ([]byte, []int) {
	return fileDescriptor_144db389311a6ed1, []int{1}
}
func (m *RetiringEscrow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RetiringEscrow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RetiringEscrow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RetiringEscrow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetiringEscrow.Merge(m, src)
}
func (m *RetiringEscrow) XXX_Size() int {
	return m.Size()
}
func (m *RetiringEscrow) XXX_DiscardUnknown() {
	xxx_messageInfo_RetiringEscrow.DiscardUnknown(m)
}

var xxx_messageInfo_RetiringEscrow proto.InternalMessageInfo

func (m *RetiringEscrow) GetReleaseAt() int64 {
	if m != nil {
		return m.ReleaseAt
	}
	return 0
}

func (m *RetiringEscrow) GetValidator() []byte {
	if m != nil {
		return m.Validator
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "earth.shieldedstaking.v1.GenesisState")
	proto.RegisterType((*RetiringEscrow)(nil), "earth.shieldedstaking.v1.RetiringEscrow")
}

func init() {
	proto.RegisterFile("earth/shieldedstaking/v1/genesis.proto", fileDescriptor_144db389311a6ed1)
}

var fileDescriptor_144db389311a6ed1 = []byte{
	// 657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcf, 0x4e, 0xdb, 0x4a,
	0x14, 0xc6, 0xe3, 0x1b, 0xe0, 0x92, 0x49, 0x08, 0x61, 0x74, 0x17, 0x23, 0x74, 0x6f, 0xc8, 0xa5,
	0x2d, 0x4a, 0xa9, 0x6a, 0x0b, 0xaa, 0x76, 0x5b, 0x15, 0x44, 0xab, 0x56, 0x2a, 0x42, 0xb6, 0x8a,
	0xd4, 0x6e, 0x2c, 0x63, 0x9f, 0x26, 0xa3, 0x38, 0x1e, 0x33, 0x67, 0x12, 0xe0, 0x2d, 0xfa, 0x16,
	0xed, 0xb2, 0x8f, 0xc1, 0x92, 0x65, 0x57, 0x55, 0x05, 0x8b, 0xbe, 0x46, 0xe5, 0xf1, 0xd8, 0xfc,
	0xa9, 0x0c, 0xdd, 0x44, 0x93, 0x2f, 0xbf, 0xef, 0x3b, 0x7f, 0x94, 0x19, 0xb2, 0x06, 0x81, 0x54,
	0x43, 0x07, 0x87, 0x1c, 0xe2, 0x08, 0x22, 0x54, 0xc1, 0x88, 0x27, 0x03, 0x67, 0xba, 0xe1, 0x0c,
	0x20, 0x01, 0xe4, 0x68, 0xa7, 0x52, 0x28, 0x41, 0x99, 0xe6, 0xec, 0x1b, 0x9c, 0x3d, 0xdd, 0x58,
	0x5e, 0x0a, 0xc6, 0x3c, 0x11, 0x8e, 0xfe, 0xcc, 0xe1, 0xe5, 0x07, 0x95, 0xa1, 0x69, 0x20, 0x83,
	0xb1, 0xc9, 0x5c, 0xb6, 0x2b, 0xb1, 0x9b, 0x65, 0x72, 0xfe, 0x9f, 0x81, 0x18, 0x08, 0x7d, 0x74,
	0xb2, 0x53, 0xae, 0xae, 0x7e, 0x9e, 0x27, 0xad, 0x57, 0x79, 0xaf, 0x9e, 0x0a, 0x14, 0xd0, 0x6d,
	0x32, 0x97, 0x97, 0x61, 0x56, 0xcf, 0xea, 0x37, 0x37, 0x7b, 0x76, 0x55, 0xef, 0xf6, 0x9e, 0xe6,
	0xb6, 0x1a, 0xa7, 0xdf, 0x57, 0x6a, 0x5f, 0x7e, 0x7e, 0x5d, 0xb7, 0x5c, 0x63, 0xa5, 0x4f, 0xc9,
	0x2c, 0xa4, 0x22, 0x1c, 0xb2, 0xbf, 0x74, 0xc6, 0x4a, 0x75, 0xc6, 0x4e, 0x86, 0xb9, 0x39, 0x4d,
	0x77, 0x09, 0x99, 0x06, 0x31, 0x8f, 0x02, 0x25, 0x24, 0xb2, 0x7a, 0xaf, 0xde, 0x6f, 0x6e, 0xf6,
	0xab, 0xbd, 0xfb, 0x05, 0xab, 0x3b, 0xdf, 0x9a, 0xc9, 0xfa, 0x70, 0xaf, 0x24, 0x50, 0x8f, 0xb4,
	0x27, 0xc9, 0x81, 0x48, 0x22, 0x5f, 0x42, 0x28, 0x64, 0x84, 0x6c, 0x46, 0x67, 0xae, 0x55, 0x67,
	0xbe, 0xd3, 0xbc, 0xab, 0x71, 0x93, 0xb8, 0x30, 0xb9, 0xa2, 0x21, 0x7d, 0x49, 0x1a, 0xa9, 0x40,
	0xae, 0xb8, 0x48, 0x90, 0xcd, 0xea, 0xbc, 0xd5, 0x5b, 0x76, 0x64, 0x50, 0x93, 0x75, 0x69, 0xa5,
	0x7d, 0xd2, 0x49, 0xe0, 0x58, 0xf9, 0x85, 0xe2, 0xf3, 0x88, 0xcd, 0xf5, 0xac, 0xfe, 0x8c, 0xdb,
	0xce, 0xf4, 0xc2, 0xf8, 0x3a, 0xa2, 0xbb, 0xa4, 0x81, 0x49, 0x90, 0xe2, 0x50, 0x28, 0x64, 0x7f,
	0xeb, 0x8a, 0xeb, 0xb7, 0x54, 0x94, 0x22, 0x15, 0x18, 0xc4, 0x9e, 0xb1, 0x14, 0x95, 0xcb, 0x08,
	0xfa, 0x9c, 0xcc, 0x4e, 0x85, 0x02, 0x64, 0xf3, 0x3a, 0xeb, 0x5e, 0x75, 0x96, 0xa7, 0x82, 0x11,
	0xec, 0x8b, 0x72, 0xb9, 0xb9, 0x8f, 0x3e, 0x22, 0x4b, 0x19, 0x04, 0x7e, 0x28, 0xc6, 0x63, 0xae,
	0xc6, 0x90, 0x28, 0x64, 0x8d, 0x5e, 0xbd, 0xdf, 0x72, 0x3b, 0xfa, 0x87, 0xed, 0x4b, 0x9d, 0x3e,
	0x24, 0xb9, 0xe6, 0x27, 0x93, 0x38, 0xe6, 0x1f, 0x39, 0x48, 0x64, 0x44, 0xb3, 0x8b, 0x5a, 0xdf,
	0x2d, 0x65, 0xfa, 0x86, 0x34, 0x73, 0x54, 0x8a, 0x6c, 0xd4, 0xe6, 0x1f, 0xb5, 0xe7, 0x8a, 0x72,
	0x46, 0x82, 0x85, 0x80, 0xf4, 0x7f, 0xd2, 0x2a, 0x26, 0xf6, 0x11, 0x0e, 0x59, 0x4b, 0xaf, 0xb6,
	0x59, 0x68, 0x1e, 0x1c, 0x52, 0x9f, 0x50, 0x9c, 0xa4, 0x69, 0x7c, 0xe2, 0x87, 0x43, 0x08, 0x47,
	0xa9, 0xe0, 0xd9, 0x1c, 0x0b, 0x77, 0x2d, 0xd8, 0xd3, 0x9e, 0xed, 0xd2, 0x62, 0x8a, 0x2f, 0xe1,
	0x0d, 0x1d, 0xe9, 0x0e, 0x69, 0xea, 0x3f, 0xb6, 0x8f, 0x47, 0x00, 0x29, 0x6b, 0xeb, 0xcb, 0x70,
	0xff, 0x8e, 0xcb, 0xe0, 0x65, 0xac, 0x4b, 0xa0, 0x3c, 0x67, 0x1b, 0x4c, 0x21, 0x89, 0x78, 0x32,
	0xf0, 0x25, 0xc4, 0x10, 0x20, 0x20, 0x5b, 0xcc, 0x37, 0x68, 0x74, 0xd7, 0xc8, 0xf4, 0x3d, 0xe9,
	0x48, 0x50, 0x5c, 0x66, 0x2c, 0x60, 0x28, 0xc5, 0x11, 0xb2, 0xce, 0x5d, 0xf7, 0xc8, 0x35, 0x8e,
	0x1d, 0x6d, 0x30, 0xe3, 0x2c, 0xca, 0x6b, 0x2a, 0xae, 0xbe, 0x25, 0xed, 0xeb, 0x20, 0xfd, 0x8f,
	0x10, 0xd3, 0x8f, 0x1f, 0x28, 0xfd, 0x5c, 0xd4, 0xdd, 0x86, 0x51, 0x5e, 0x28, 0xfa, 0x2f, 0x69,
	0x94, 0x77, 0x51, 0x3f, 0x04, 0x2d, 0xf7, 0x52, 0xd8, 0xda, 0x3b, 0x3d, 0xef, 0x5a, 0x67, 0xe7,
	0x5d, 0xeb, 0xc7, 0x79, 0xd7, 0xfa, 0x74, 0xd1, 0xad, 0x9d, 0x5d, 0x74, 0x6b, 0xdf, 0x2e, 0xba,
	0xb5, 0x0f, 0xcf, 0x06, 0x5c, 0x0d, 0x27, 0x07, 0x76, 0x28, 0xc6, 0x8e, 0xee, 0xf9, 0x71, 0x02,
	0xea, 0x48, 0xc8, 0x51, 0xfe, 0xcd, 0x39, 0xfe, 0xed, 0xcd, 0x53, 0x27, 0x29, 0xe0, 0xc1, 0x9c,
	0x7e, 0xd1, 0x9e, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xb5, 0xf7, 0x01, 0x95, 0x05, 0x00,
	0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RetiringEscrows) > 0 {
		for iNdEx := len(m.RetiringEscrows) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RetiringEscrows[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if len(m.PendingReleases) > 0 {
		for iNdEx := len(m.PendingReleases) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PendingReleases[iNdEx])
			copy(dAtA[i:], m.PendingReleases[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.PendingReleases[iNdEx])))
			i--
			dAtA[i] = 0x7a
		}
	}
	if m.EpochSweep != nil {
		{
			size, err := m.EpochSweep.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x72
	}
	if len(m.SupplyCheckpoints) > 0 {
		for iNdEx := len(m.SupplyCheckpoints) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SupplyCheckpoints[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if m.SnapshotSeq != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SnapshotSeq))
		i--
		dAtA[i] = 0x60
	}
	if len(m.StakeRoots) > 0 {
		for iNdEx := len(m.StakeRoots) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakeRoots[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.StakeNullifiers) > 0 {
		for iNdEx := len(m.StakeNullifiers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.StakeNullifiers[iNdEx])
			copy(dAtA[i:], m.StakeNullifiers[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.StakeNullifiers[iNdEx])))
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.StakeCommitments) > 0 {
		for iNdEx := len(m.StakeCommitments) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.StakeCommitments[iNdEx])
			copy(dAtA[i:], m.StakeCommitments[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.StakeCommitments[iNdEx])))
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.Votes) > 0 {
		for iNdEx := len(m.Votes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Votes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Snapshots) > 0 {
		for iNdEx := len(m.Snapshots) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Snapshots[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.NextPositionId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextPositionId))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Positions) > 0 {
		for iNdEx := len(m.Positions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Positions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.UnbondRecords) > 0 {
		for iNdEx := len(m.UnbondRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UnbondRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Validators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Epoch != nil {
		{
			size, err := m.Epoch.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *RetiringEscrow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RetiringEscrow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RetiringEscrow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x12
	}
	if m.ReleaseAt != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ReleaseAt))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.Epoch != nil {
		l = m.Epoch.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.Validators) > 0 {
		for _, e := range m.Validators {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.UnbondRecords) > 0 {
		for _, e := range m.UnbondRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Positions) > 0 {
		for _, e := range m.Positions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextPositionId != 0 {
		n += 1 + sovGenesis(uint64(m.NextPositionId))
	}
	if len(m.Snapshots) > 0 {
		for _, e := range m.Snapshots {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Votes) > 0 {
		for _, e := range m.Votes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.StakeCommitments) > 0 {
		for _, b := range m.StakeCommitments {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.StakeNullifiers) > 0 {
		for _, b := range m.StakeNullifiers {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.StakeRoots) > 0 {
		for _, e := range m.StakeRoots {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.SnapshotSeq != 0 {
		n += 1 + sovGenesis(uint64(m.SnapshotSeq))
	}
	if len(m.SupplyCheckpoints) > 0 {
		for _, e := range m.SupplyCheckpoints {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.EpochSweep != nil {
		l = m.EpochSweep.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.PendingReleases) > 0 {
		for _, b := range m.PendingReleases {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RetiringEscrows) > 0 {
		for _, e := range m.RetiringEscrows {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *RetiringEscrow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReleaseAt != 0 {
		n += 1 + sovGenesis(uint64(m.ReleaseAt))
	}
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Epoch == nil {
				m.Epoch = &Epoch{}
			}
			if err := m.Epoch.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, ValidatorState{})
			if err := m.Validators[len(m.Validators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnbondRecords = append(m.UnbondRecords, UnbondRecord{})
			if err := m.UnbondRecords[len(m.UnbondRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Positions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Positions = append(m.Positions, Position{})
			if err := m.Positions[len(m.Positions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextPositionId", wireType)
			}
			m.NextPositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextPositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snapshots", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Snapshots = append(m.Snapshots, ProposalSnapshot{})
			if err := m.Snapshots[len(m.Snapshots)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Votes = append(m.Votes, StakeVote{})
			if err := m.Votes[len(m.Votes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeCommitments", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakeCommitments = append(m.StakeCommitments, make([]byte, postIndex-iNdEx))
			copy(m.StakeCommitments[len(m.StakeCommitments)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeNullifiers", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakeNullifiers = append(m.StakeNullifiers, make([]byte, postIndex-iNdEx))
			copy(m.StakeNullifiers[len(m.StakeNullifiers)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeRoots", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakeRoots = append(m.StakeRoots, StakeRoot{})
			if err := m.StakeRoots[len(m.StakeRoots)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnapshotSeq", wireType)
			}
			m.SnapshotSeq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SnapshotSeq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplyCheckpoints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupplyCheckpoints = append(m.SupplyCheckpoints, SupplyCheckpoint{})
			if err := m.SupplyCheckpoints[len(m.SupplyCheckpoints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochSweep", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EpochSweep == nil {
				m.EpochSweep = &EpochSweep{}
			}
			if err := m.EpochSweep.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingReleases", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingReleases = append(m.PendingReleases, make([]byte, postIndex-iNdEx))
			copy(m.PendingReleases[len(m.PendingReleases)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetiringEscrows", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RetiringEscrows = append(m.RetiringEscrows, RetiringEscrow{})
			if err := m.RetiringEscrows[len(m.RetiringEscrows)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RetiringEscrow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RetiringEscrow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RetiringEscrow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleaseAt", wireType)
			}
			m.ReleaseAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReleaseAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = append(m.Validator[:0], dAtA[iNdEx:postIndex]...)
			if m.Validator == nil {
				m.Validator = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
