// Command privacyfixtures writes a Prover.toml for the membership or transfer
// circuit (earth-network-mobile/circuits) from trees and derivations built with
// zk/merkle and zk/privacy, plus the public inputs the chain would supply
// (public_inputs.expected, 32-byte big-endian fields in ABI order). Running
// nargo execute on the toml is the Go<->Noir parity check: the circuit only
// accepts if every hash, path and derivation agrees.
//
//	go run ./tools/privacyfixtures <membership|membership-zeroed|transfer> <outdir>
//
// membership-zeroed builds the same witness after the chain zeroed the leaf;
// the circuit must reject it.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/consensys/gnark-crypto/ecc/bn254/fr"

	"github.com/earth-network/earth/zk/merkle"
	"github.com/earth-network/earth/zk/privacy"
)

// det is a deterministic pseudo-random field element, so fixtures are stable.
func det(label string, i uint64) fr.Element {
	return privacy.H(privacy.AssetID("fixture/"+label), privacy.U64(i))
}

func hex(e fr.Element) string {
	b := e.Bytes()
	return fmt.Sprintf("0x%x", b[:])
}

func q(e fr.Element) string { return fmt.Sprintf("%q", hex(e)) }

func arr(es []fr.Element) string {
	parts := make([]string, len(es))
	for i, e := range es {
		parts[i] = q(e)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: privacyfixtures <membership|membership-zeroed|transfer> <outdir>")
		os.Exit(2)
	}
	out := os.Args[2]
	if err := os.MkdirAll(out, 0o755); err != nil {
		panic(err)
	}
	var toml string
	var pub []fr.Element
	switch os.Args[1] {
	case "membership":
		toml, pub = membership(false)
	case "membership-zeroed":
		toml, pub = membership(true)
	case "transfer":
		toml, pub = transfer()
	default:
		fmt.Fprintf(os.Stderr, "unknown circuit %q\n", os.Args[1])
		os.Exit(2)
	}
	must(os.WriteFile(filepath.Join(out, "Prover.toml"), []byte(toml), 0o644))
	var raw []byte
	for _, e := range pub {
		b := e.Bytes()
		raw = append(raw, b[:]...)
	}
	must(os.WriteFile(filepath.Join(out, "public_inputs.expected"), raw, 0o644))
}

func mustEl(e fr.Element, err error) fr.Element {
	must(err)
	return e
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func membership(zeroed bool) (string, []fr.Element) {
	t := merkle.NewMem()
	const ours = 13
	idSecret := det("id_secret", 0)
	dscKey := det("dsc", 0)
	const activatedAt = uint64(1_790_000_000)
	for i := uint64(0); i < 21; i++ {
		leaf := privacy.IdentityLeaf(privacy.IDC(det("other", i)), det("dsc", i%3), 1_780_000_000+i)
		if i == ours {
			leaf = privacy.IdentityLeaf(privacy.IDC(idSecret), dscKey, activatedAt)
		}
		_, err := t.Append(leaf)
		must(err)
	}
	must(t.Update(3, fr.Element{})) // an expired registration elsewhere
	if zeroed {
		must(t.Update(ours, fr.Element{}))
	}
	// the path is taken before zeroing in the negative case: a stale path
	// against the post-zeroing root must fail.
	t2 := merkle.NewMem()
	for i := uint64(0); i < t.Size(); i++ {
		_, _ = t2.Append(mustEl(t.Leaf(i)))
	}
	if zeroed {
		must(t2.Update(ours, privacy.IdentityLeaf(privacy.IDC(idSecret), dscKey, activatedAt)))
	}
	sib, err := t2.Path(ours)
	must(err)

	root := mustEl(t.Root())
	scope := privacy.AssetID("claim:20360")
	nullifier := privacy.ScopeNullifier(idSecret, scope)
	signal := det("signal", 0)
	excluded := det("dsc", 99)
	maxAct := privacy.U64(activatedAt + 86_400)

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by tools/privacyfixtures. Do not edit.\n")
	fmt.Fprintf(&b, "id_secret = %s\ndsc_key = %s\nactivated_at = \"%d\"\nleaf_index = \"%d\"\n",
		q(idSecret), q(dscKey), activatedAt, ours)
	fmt.Fprintf(&b, "siblings = %s\n", arr(sib[:]))
	fmt.Fprintf(&b, "root = %s\nscope = %s\nnullifier = %s\nsignal = %s\nexcluded_dsc = %s\nmax_activation = \"%d\"\n",
		q(root), q(scope), q(nullifier), q(signal), q(excluded), activatedAt+86_400)
	return b.String(), []fr.Element{root, scope, nullifier, signal, excluded, maxAct}
}

func transfer() (string, []fr.Element) {
	t := merkle.NewMem()
	nk := det("nk", 0)
	opk := privacy.OwnerPK(nk)
	assetA := privacy.AssetID("uanml")
	erth := privacy.AssetID("uerth")
	inVal := [3]uint64{700_000, 300_000, 50_000}
	outVal := [3]uint64{600_000, 350_000, 40_000}
	const fee, vPubOut = uint64(10_000), uint64(50_000)
	assets := [3]fr.Element{assetA, assetA, erth}
	positions := [3]uint64{4, 7, 9}
	var rho, rcm [3]fr.Element
	for i := range 3 {
		rho[i], rcm[i] = det("rho", uint64(i)), det("rcm", uint64(i))
	}
	next := 0
	for p := uint64(0); p < 12; p++ {
		cm := privacy.CM(erth, p+1, det("otherpc", p))
		if next < 3 && p == positions[next] {
			cm = privacy.CM(assets[next], inVal[next], privacy.PC(opk, rho[next], rcm[next]))
			next++
		}
		_, err := t.Append(cm)
		must(err)
	}
	root := mustEl(t.Root())

	var paths [3]string
	var nf, cmOut, outPC [3]fr.Element
	for i := range 3 {
		sib, err := t.Path(positions[i])
		must(err)
		paths[i] = arr(sib[:])
		nf[i] = privacy.NF(nk, rho[i], uint32(positions[i]))
		outPC[i] = privacy.PC(privacy.OwnerPK(det("recipient", uint64(i))), det("orho", uint64(i)), det("orcm", uint64(i)))
		cmOut[i] = privacy.CM(assets[i], outVal[i], outPC[i])
	}
	signal := det("signal", 1)

	u := func(v [3]uint64) string {
		return fmt.Sprintf("[\"%d\", \"%d\", \"%d\"]", v[0], v[1], v[2])
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by tools/privacyfixtures. Do not edit.\n")
	fmt.Fprintf(&b, "asset = %s\nnk = %s\n", q(assetA), q(nk))
	fmt.Fprintf(&b, "in_value = %s\nin_rho = %s\nin_rcm = %s\nin_pos = %s\n",
		u(inVal), arr(rho[:]), arr(rcm[:]), u(positions))
	fmt.Fprintf(&b, "in_path = [%s]\n", strings.Join(paths[:], ", "))
	fmt.Fprintf(&b, "out_value = %s\nout_pc = %s\n", u(outVal), arr(outPC[:]))
	fmt.Fprintf(&b, "root = %s\nnf = %s\ncm_out = %s\nfee = \"%d\"\nv_pub_out = \"%d\"\nasset_pub = %s\nsignal = %s\n",
		q(root), arr(nf[:]), arr(cmOut[:]), fee, vPubOut, q(assetA), q(signal))

	pub := []fr.Element{root}
	pub = append(pub, nf[:]...)
	pub = append(pub, cmOut[:]...)
	pub = append(pub, privacy.U64(fee), privacy.U64(vPubOut), assetA, signal)
	return b.String(), pub
}
